- Asset/data/asset/functions/artifact/0900.pure_water_bracelet/give/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/0900.pure_water_bracelet/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0900.pure_water_bracelet/register.mcfunction
- Asset/data/asset/functions/artifact/0900.pure_water_bracelet/trigger/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/0900.pure_water_bracelet/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/0900.pure_water_bracelet/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0900.pure_water_bracelet/trigger/_index.d.mcfunction
- Asset/data/asset/tags/functions/artifact/damage/fire.json
- Asset/data/asset/tags/functions/artifact/give.json
- Asset/data/asset/tags/functions/artifact/register.json
> 【神器900】清水のブレスレットを作成

- Asset/data/asset/functions/trader/0011.redstone_merchant/register/.mcfunction
- Asset/data/asset/functions/trader/0011.redstone_merchant/register/register.mcfunction
> 赤石商人のファイル指定ミスを修正

- Asset/data/asset/functions/effect/0228.rubeus_resonance/_/register.mcfunction
- Asset/data/asset/functions/effect/0228.rubeus_resonance/_/tick.mcfunction
- Asset/data/asset/functions/effect/0228.rubeus_resonance/register.mcfunction
- Asset/data/asset/functions/effect/0228.rubeus_resonance/tick/.mcfunction
- Asset/data/asset/functions/effect/0229.sapphirus_resonance/_/register.mcfunction
- Asset/data/asset/functions/effect/0229.sapphirus_resonance/_/tick.mcfunction
- Asset/data/asset/functions/effect/0229.sapphirus_resonance/register.mcfunction
- Asset/data/asset/functions/effect/0229.sapphirus_resonance/tick/.mcfunction
- Asset/data/asset/tags/functions/effect/register.json
- Asset/data/asset/tags/functions/effect/tick.json
> [Effect228-229] 共鳴・紅 ＆ 共鳴・蒼 バフを作成

- Asset/data/asset/functions/artifact/0372.water_magic/trigger/3.2.damage.mcfunction
- Asset/data/asset/functions/artifact/0372.water_magic/trigger/_index.d.mcfunction
> ♻️ [神器372] ウォーターマジックのコマンドの改善

- Asset/data/asset/functions/artifact/0801.red_secret_stone/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0801.red_secret_stone/trigger/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/0801.red_secret_stone/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/0801.red_secret_stone/trigger/3.main.mcfunction
- Asset/data/asset/tags/functions/artifact/damage.json
- Asset/data/asset/tags/functions/artifact/damage/from_entity/.json
> ⚖️ [神器801] 赤い謎の秘石のリワーク

- Asset/data/asset/functions/artifact/0920.dal_i_thalion/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0920.dal_i_thalion/trigger/4.schedule.mcfunction
- Asset/data/asset/functions/artifact/0920.dal_i_thalion/trigger/5.effect_clear.mcfunction
・CDを変更
・デバフ解除をEffectAsset仕様に
・IMP-Docを追加
> ⚖️ [神器920] ダル・イ・サリオンの仕様変更

- Asset/data/asset/functions/mob/0124.skull_harpy/attack/2.attack.mcfunction
- Asset/data/asset/functions/mob/0124.skull_harpy/tick/2.1.motion.mcfunction
色々無駄を省くのと
ハード以上で浮遊を付与する能力を追加
ただしレイブンよりは弱めの浮遊
> ⚖️ [Mob124] スカルハーピィの修正とハード対応

- Asset/data/asset/functions/artifact/0361.rainbow_crystal/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0361.rainbow_crystal/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0361.rainbow_crystal/trigger/4.damage.mcfunction
Loreとコマンドについてのみの修正
性能については一切変更を加えていない
> ♻️ [神器361] 極虹の水晶の修正

- Asset/data/asset/functions/artifact/0910.ignite/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0910.ignite/trigger/3.main.mcfunction
> ⚖️ [神器910] イグナイトの調整

- Asset/data/asset/functions/mob/0124.skull_harpy/tick/2.1.motion.mcfunction
- Asset/data/asset/functions/mob/0124.skull_harpy/tick/2.tick.mcfunction
- Asset/data/asset/functions/mob/0182.skull_raven/tick/2.tick.mcfunction
- Asset/data/asset/functions/mob/0182.skull_raven/tick/3.motion.mcfunction
- Asset/data/asset/functions/mob/0233.honey_flyer/tick/2.tick.mcfunction
- Asset/data/asset/functions/mob/0233.honey_flyer/tick/3.motion.mcfunction
該当Mob：スカルハーピィ、スカルレイブン、ハニーフライヤー
> ⚖️ 飛行系Mobの索敵範囲を縮小

- Asset/data/asset/functions/artifact/0729.bloody_pride/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0801.red_secret_stone/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0897.lightning_broach/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0898.gale_pendant/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0899.flame_ring/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0960.heavy_charm/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0961.light_charm/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0978.fire_charm/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0979.water_charm/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0980.thunder_charm/give/2.give.mcfunction
> 🚸 一部ホットバー神器に重複可能かの説明を追加

- Asset/data/asset/functions/artifact/0844.closed_eyes_of_love/give/2.give.mcfunction
> ⚖️ [神器844] 閉じた恋の瞳のMP調整

- Asset/data/asset/functions/artifact/0253.holy_barrier/give/2.give.mcfunction
> ♿ [神器253] ホーリー・バリアの中身を棒に変更

- Asset/data/asset/tags/functions/effect/end.json
- Asset/data/asset/tags/functions/effect/given.json
> 🩹 EffectAssetのfunctionTagのミスを修正

- Asset/data/asset/functions/artifact/1083.tablet_of_oracle/give/2.give.mcfunction
- Asset/data/asset/functions/effect/0248.oracle_physical_attack/register.mcfunction
- Asset/data/asset/functions/effect/0249.oracle_physical_defense/register.mcfunction
- Asset/data/asset/functions/effect/0250.oracle_magic_attack/register.mcfunction
- Asset/data/asset/functions/effect/0251.oracle_magic_defense/register.mcfunction
> ⚖️ [神器1083] 神託の刻まれた石板の効果の調整

- Asset/data/asset/loot_tables/mob/death/0046.clock_of_despair.json
- Asset/data/asset/loot_tables/mob/death/0083.thunder_trifler.json
- Asset/data/asset/loot_tables/mob/death/0219.aorta.json
- Asset/data/asset/loot_tables/mob/death/0220.vena_cana.json
- Asset/data/asset/loot_tables/mob/death/0253.parasitic_soldiers.json
- Asset/data/asset/loot_tables/mob/death/0254.headless.json
- Asset/data/asset/loot_tables/mob/death/0255.dependence_eye.json
- Asset/data/asset/loot_tables/mob/death/0273.hell_blade.json
- Asset/data/asset/loot_tables/mob/death/0274.death_saw_jiki.json
> 🩹 一部のMobのルートテーブルを修正

- Asset/data/asset/functions/artifact/0933.auto_torch/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0933.auto_torch/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/0933.auto_torch/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0933.auto_torch/trigger/_index.d.mcfunction
- Asset/data/asset/functions/artifact/0933.auto_torch/trigger/can_set_check.mcfunction
視点の先にも置くように
スニークを指定ない状態かつ、下をむいている場合は無効化するように
CDを半減
A型人種を破壊
> ♻️ [神器933] オートトーチの改善

- Asset/data/asset/functions/artifact/0183.answer_to_the_ultimate_question_of_life_the_universe_and_everything/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0183.answer_to_the_ultimate_question_of_life_the_universe_and_everything/trigger/3.main.mcfunction
- Asset/data/asset/functions/effect/0217.the_answer/_/end.mcfunction
- Asset/data/asset/functions/effect/0217.the_answer/_/given.mcfunction
- Asset/data/asset/functions/effect/0217.the_answer/_/register.mcfunction
- Asset/data/asset/functions/effect/0217.the_answer/_/remove.mcfunction
- Asset/data/asset/functions/effect/0217.the_answer/_/tick.mcfunction
- Asset/data/asset/functions/effect/0217.the_answer/end/.mcfunction
- Asset/data/asset/functions/effect/0217.the_answer/given/.mcfunction
- Asset/data/asset/functions/effect/0217.the_answer/modifier/add.mcfunction
- Asset/data/asset/functions/effect/0217.the_answer/modifier/remove.mcfunction
- Asset/data/asset/functions/effect/0217.the_answer/register.mcfunction
- Asset/data/asset/functions/effect/0217.the_answer/remove/.mcfunction
- Asset/data/asset/functions/effect/0217.the_answer/tick/.mcfunction
- Asset/data/asset/tags/functions/effect/end.json
- Asset/data/asset/tags/functions/effect/given.json
- Asset/data/asset/tags/functions/effect/register.json
- Asset/data/asset/tags/functions/effect/remove.json
- Asset/data/asset/tags/functions/effect/tick.json
Fixed #105 
多分ぶっ壊れかな～～～～～～～～～～～～～～～
> 🍱 [神器183] 生命、宇宙、そして万物についての究極の疑問の答えの仕様変更

- Asset/data/asset/functions/mob/0189.water_mage/tick/2.tick.mcfunction
- Asset/data/asset/functions/mob/0189.water_mage/tick/3.summon_water_magic.mcfunction
- Asset/data/asset/functions/mob/0214.water_magic/tick/2.tick.mcfunction
- Asset/data/asset/functions/mob/0214.water_magic/tick/4.damage_and_vfx.mcfunction
フレイムとサンダーに比べると地味だけどいや～～～～～～～～な強化
> ⚖️ [Mob189] ウォーターメイジのハード対応

- Asset/data/asset/functions/mob/0084.falcios_priest/tick/3.heal.mcfunction
> 🐛 [Mob84] ファルシオスの神官のバグ修正

- Asset/data/asset/functions/mob/0258.enemy_teleporter/tick/branch.mcfunction
- Asset/data/asset/functions/mob/0258.enemy_teleporter/tick/teleport.mcfunction
- Asset/data/asset/functions/mob/0258.enemy_teleporter/tick/weak_teleport.mcfunction
ボスをテレポートするコマンドが組まれていたため、テレポートしないように調整
> ⚖️ [Mob258] 歪みの魔導書がボスをテレポートしないように

- Asset/data/asset/functions/mob/0084.falcios_priest/tick/3.heal.mcfunction
> 🩹 [Mob84] ファルシオスの神官 演出のバグ修正

- Asset/data/asset/functions/effect/0124.darkness/_/end.mcfunction
- Asset/data/asset/functions/effect/0124.darkness/_/register.mcfunction
- Asset/data/asset/functions/effect/0124.darkness/_/remove.mcfunction
- Asset/data/asset/functions/effect/0124.darkness/_/tick.mcfunction
- Asset/data/asset/functions/effect/0124.darkness/end/.mcfunction
- Asset/data/asset/functions/effect/0124.darkness/register.mcfunction
- Asset/data/asset/functions/effect/0124.darkness/remove/.mcfunction
- Asset/data/asset/functions/effect/0124.darkness/tick/.mcfunction
- Asset/data/asset/tags/functions/effect/end.json
- Asset/data/asset/tags/functions/effect/register.json
- Asset/data/asset/tags/functions/effect/remove.json
- Asset/data/asset/tags/functions/effect/tick.json
> 🍱 [Effect124] 汎用エフェクト 暗闇を追加

- .vscode/settings.json
> ObjectAsset用のテンプレートをこっちにも追加した

- .vscode/settings.json
> Object Assetのテンプレートの修正

- Asset/data/asset/functions/artifact/0219.abyss_sword/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0248.bow_of_vinderre/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0328.attract_hook_shot/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0346.gather_around/trigger/3.main.mcfunction
- Asset/data/asset/functions/mob/0046.clock_of_despair/summon/2.summon.mcfunction
- Asset/data/asset/functions/mob/0258.enemy_teleporter/tick/teleport.mcfunction
- Asset/data/minecraft/functions/declares.d.mcfunction
本来TPしてはならないものに対してTPさせないように移動不可タグを追加しました
> 移動不可タグ Immovable を追加

- .vscode/settings.json
> AssetリポジトリへのObjectのInit処理のテンプレ登録

- Asset/data/asset/functions/effect/0212.lunatic_moon/register.mcfunction
- Asset/data/asset/functions/effect/0213.reflecting_sky/register.mcfunction
- Asset/data/asset/functions/effect/0214.quick_charge/register.mcfunction
- Asset/data/asset/functions/effect/0215.purification/register.mcfunction
- Asset/data/asset/functions/effect/0218.heavy_weight/register.mcfunction
- Asset/data/asset/functions/effect/0219.blood_eater/register.mcfunction
- Asset/data/asset/functions/effect/0220.dream_of_burning_butterfly/register.mcfunction
- Asset/data/asset/functions/effect/0221.hunters_run/register.mcfunction
- Asset/data/asset/functions/effect/0228.rubeus_resonance/register.mcfunction
- Asset/data/asset/functions/effect/0229.sapphirus_resonance/register.mcfunction
- Asset/data/asset/functions/effect/0230.farothdal/register.mcfunction
- Asset/data/asset/functions/effect/0231.wandering_dream/register.mcfunction
- Asset/data/asset/functions/effect/0248.oracle_physical_attack/register.mcfunction
- Asset/data/asset/functions/effect/0249.oracle_physical_defense/register.mcfunction
- Asset/data/asset/functions/effect/0250.oracle_magic_attack/register.mcfunction
- Asset/data/asset/functions/effect/0251.oracle_magic_defense/register.mcfunction
- Asset/data/asset/functions/effect/0253.purifying_indigo/register.mcfunction
- Asset/data/asset/functions/effect/0260.life_steal/register.mcfunction
- Asset/data/asset/functions/effect/0603.domination/register.mcfunction
- Asset/data/asset/functions/effect/0605.aurora_corrosion/tick/mp_reduce.mcfunction
- Asset/data/asset/functions/effect/0607.sedation/register.mcfunction
- Asset/data/asset/functions/effect/0608.sinking/register.mcfunction
- Asset/data/asset/functions/effect/0612.infringement/register.mcfunction
- Asset/data/asset/functions/effect/0613.white_curse/register.mcfunction
> 既存エフェクトの説明文の規格化

- Asset/data/asset/functions/artifact/1047.life_steal_emblem/trigger/3.main.mcfunction
- Asset/data/asset/functions/effect/0260.life_steal/modifier/add.mcfunction
- Asset/data/asset/functions/effect/0260.life_steal/modifier/remove.mcfunction
いくらなんでもミスが多すぎた
ちょっと魂命の徽章にも修正が入ってる
> [Effect260] 魂命の修正

- Asset/data/asset/functions/effect/0613.white_curse/modifier/add.mcfunction
- Asset/data/asset/functions/mob/0364.white_magic/tick/attack.mcfunction
- Asset/data/asset/functions/mob/0364.white_magic/tick/debuff.mcfunction
> [Mob363] 白呪の魔導書の調整

- Asset/data/asset/functions/mob/0075.watermelon/summon/.mcfunction
- Asset/data/asset/functions/mob/0077.golden_watermelon/summon/.mcfunction
> [Mob75 & 77] スイカと金スイカのdisplayの表示の問題を修正

- .vscode/settings.json
・Implement生成の部分が吹っ飛んだ
・Extendsの書き方毎回忘れるので、それもテンプレートとして生成するようにした。もちろんオプション！
> 👽️ ObjectAsset v2.1 用にテンプレートを修正

- Asset/data/asset/functions/object/2031.giant_pumpkin/_index.d.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/detect_hit_block/.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/detect_hit_block/check.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/detect_hit_entity/.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/detect_hit_entity/check.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/hit_entity/.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/hit_entity/beginning_hit.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/init/.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/kill/.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/load.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/register.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/summon/.m.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/summon/.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/summon/debug.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/tick/.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/tick/beginning_spin.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/tick/high_speed_spin.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/tick/set_spin.mcfunction
- Asset/data/asset/functions/object/alias/2031/detect_hit_block.mcfunction
- Asset/data/asset/functions/object/alias/2031/detect_hit_entity.mcfunction
- Asset/data/asset/functions/object/alias/2031/hit_entity.mcfunction
- Asset/data/asset/functions/object/alias/2031/init.mcfunction
- Asset/data/asset/functions/object/alias/2031/kill.mcfunction
- Asset/data/asset/functions/object/alias/2031/register.mcfunction
- Asset/data/asset/functions/object/alias/2031/summon.mcfunction
- Asset/data/asset/functions/object/alias/2031/tick.mcfunction
- Asset/data/asset/tags/functions/object/load.json
> ✨ [Object2031] 巨大カボチャを作成

- Asset/data/asset/functions/object/2031.giant_pumpkin/detect_hit_entity/.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/detect_hit_entity/check.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/hit_entity/beginning_hit.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/kill/.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/register.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/tick/.mcfunction
> 🩹 [Object2031] 巨大カボチャのミスを修正

- Asset/data/asset/functions/artifact/0769.shaking_splash/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0769.shaking_splash/trigger/5.beam.mcfunction
> ⚖️ [神器769] シェイキングスプラッシュの火力を調整

- Asset/data/asset/functions/object/2063.damage_area/_index.d.mcfunction
- Asset/data/asset/functions/object/2063.damage_area/init/.mcfunction
- Asset/data/asset/functions/object/2063.damage_area/register.mcfunction
- Asset/data/asset/functions/object/2063.damage_area/summon/.mcfunction
- Asset/data/asset/functions/object/2063.damage_area/summon/debug.mcfunction
- Asset/data/asset/functions/object/2063.damage_area/tick/.mcfunction
- Asset/data/asset/functions/object/alias/2063/init.mcfunction
- Asset/data/asset/functions/object/alias/2063/register.mcfunction
- Asset/data/asset/functions/object/alias/2063/summon.mcfunction
- Asset/data/asset/functions/object/alias/2063/tick.mcfunction
色、サイズ、表示時間を調整できるように作った。
もっと良いテクスチャを用意できる人募集中。
> 🍱 [Object2063] 汎用円形ダメージエリアを作った

- Asset/data/asset/functions/artifact/1043.gamma_ray/trigger/6.cast.mcfunction
> 🩹 [神器1043] ガンマレイのダメージ処理の修正

- Asset/data/asset/tags/functions/artifact/give.json
> 🩹 [神器730] 湖鏡映天がgive.jsonに登録されていなかった問題を修正

- Asset/data/asset/functions/mob/0056.thunder_trifler/register.mcfunction
- Asset/data/asset/functions/mob/0083.thunder_trifler/register.mcfunction
> ⚖️ [Mob56,83] 雷弄者のナーフ

- Asset/data/asset/functions/artifact/1078.pigeon_blood/trigger/3.main.mcfunction
> 🚸 [神器1078] ピジョンブラッドの演出の調整

- Asset/data/asset/functions/artifact/0973.call_rod_spirit/trigger/2.check_condition.mcfunction
クールダウンメッセージと召喚してますが同時にどっちも出てるのは微妙かった
> 🚸 [神器973] コール: バラージュスピリットの使用不可メッセージの仕様を調整

- Asset/data/asset/functions/artifact/1145.nurse_call/give/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/1145.nurse_call/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1145.nurse_call/register.mcfunction
- Asset/data/asset/functions/artifact/1145.nurse_call/trigger/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/1145.nurse_call/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/1145.nurse_call/trigger/3.main.mcfunction
- Asset/data/asset/functions/object/1060.medic/init/.mcfunction
- Asset/data/asset/functions/object/1060.medic/register.mcfunction
- Asset/data/asset/functions/object/1060.medic/summon/.mcfunction
- Asset/data/asset/functions/object/1060.medic/summon/debug.mcfunction
- Asset/data/asset/functions/object/1060.medic/summon/macro.m.mcfunction
- Asset/data/asset/functions/object/1060.medic/tick/.mcfunction
- Asset/data/asset/functions/object/1060.medic/tick/circle.mcfunction
- Asset/data/asset/functions/object/1060.medic/tick/heal.mcfunction
- Asset/data/asset/functions/object/1060.medic/tick/remove.mcfunction
- Asset/data/asset/functions/object/1060.medic/tick/vfx.mcfunction
- Asset/data/asset/functions/object/alias/1060/init.mcfunction
- Asset/data/asset/functions/object/alias/1060/register.mcfunction
- Asset/data/asset/functions/object/alias/1060/summon.mcfunction
- Asset/data/asset/functions/object/alias/1060/tick.mcfunction
- Asset/data/asset/tags/functions/artifact/click.carrot_on_a_stick.json
- Asset/data/asset/tags/functions/artifact/give.json
- Asset/data/asset/tags/functions/artifact/register.json
> 🍱 [神器1145] ナースコールを作成

- Asset/data/asset/functions/artifact/0796.log4shell/give/2.give.mcfunction
> [神器796] Log4ShellのURLを変更

- Asset/data/asset/functions/effect/0101.attack_base_debuff/_/end.mcfunction
- Asset/data/asset/functions/effect/0101.attack_base_debuff/_/given.mcfunction
- Asset/data/asset/functions/effect/0101.attack_base_debuff/_/re-given.mcfunction
- Asset/data/asset/functions/effect/0101.attack_base_debuff/_/register.mcfunction
- Asset/data/asset/functions/effect/0101.attack_base_debuff/_/remove.mcfunction
- Asset/data/asset/functions/effect/0101.attack_base_debuff/end/.mcfunction
- Asset/data/asset/functions/effect/0101.attack_base_debuff/given/.mcfunction
- Asset/data/asset/functions/effect/0101.attack_base_debuff/modifier/add.mcfunction
- Asset/data/asset/functions/effect/0101.attack_base_debuff/modifier/remove.mcfunction
- Asset/data/asset/functions/effect/0101.attack_base_debuff/re-given/.mcfunction
- Asset/data/asset/functions/effect/0101.attack_base_debuff/register.mcfunction
- Asset/data/asset/functions/effect/0101.attack_base_debuff/remove/.mcfunction
- Asset/data/asset/tags/functions/effect/end.json
- Asset/data/asset/tags/functions/effect/given.json
- Asset/data/asset/tags/functions/effect/re-given.json
- Asset/data/asset/tags/functions/effect/register.json
- Asset/data/asset/tags/functions/effect/remove.json
- Asset/data/asset/tags/functions/effect/tick.json
> :bento: [Effect101] 与ダメージ低下デバフを追加

- Asset/data/asset/functions/effect/0107.defense_base_debuff/_/end.mcfunction
- Asset/data/asset/functions/effect/0107.defense_base_debuff/_/given.mcfunction
- Asset/data/asset/functions/effect/0107.defense_base_debuff/_/re-given.mcfunction
- Asset/data/asset/functions/effect/0107.defense_base_debuff/_/register.mcfunction
- Asset/data/asset/functions/effect/0107.defense_base_debuff/_/remove.mcfunction
- Asset/data/asset/functions/effect/0107.defense_base_debuff/end/.mcfunction
- Asset/data/asset/functions/effect/0107.defense_base_debuff/given/.mcfunction
- Asset/data/asset/functions/effect/0107.defense_base_debuff/modifier/add.mcfunction
- Asset/data/asset/functions/effect/0107.defense_base_debuff/modifier/remove.mcfunction
- Asset/data/asset/functions/effect/0107.defense_base_debuff/re-given/.mcfunction
- Asset/data/asset/functions/effect/0107.defense_base_debuff/register.mcfunction
- Asset/data/asset/functions/effect/0107.defense_base_debuff/remove/.mcfunction
- Asset/data/asset/tags/functions/effect/end.json
- Asset/data/asset/tags/functions/effect/given.json
- Asset/data/asset/tags/functions/effect/re-given.json
- Asset/data/asset/tags/functions/effect/register.json
- Asset/data/asset/tags/functions/effect/remove.json
> :bento: [Effect107] 被ダメージ上昇デバフを追加

- Asset/data/asset/functions/mob/10010.sandbag1a/register.mcfunction
- Asset/data/asset/functions/mob/10011.sandbag2a/register.mcfunction
- Asset/data/asset/functions/mob/10012.sandbag3a/register.mcfunction
- Asset/data/asset/functions/mob/10013.sandbag4a/register.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/attack/.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/attack/add_damage_increase_debug/.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/attack/add_damage_increase_debug/add.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/bossbar/add.m.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/bossbar/remove.m.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/bossbar/update.m.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/death/.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/hurt/.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/init/.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/load.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/register.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/remove/.mcfunction
- Asset/data/asset/functions/mob/2000.abstract_angel/update_bossbar/.mcfunction
- Asset/data/asset/functions/mob/alias/2000/attack.mcfunction
- Asset/data/asset/functions/mob/alias/2000/death.mcfunction
- Asset/data/asset/functions/mob/alias/2000/hurt.mcfunction
- Asset/data/asset/functions/mob/alias/2000/init.mcfunction
- Asset/data/asset/functions/mob/alias/2000/register.mcfunction
- Asset/data/asset/functions/mob/alias/2000/remove.mcfunction
- Asset/data/asset/functions/mob/alias/2000/update_bossbar.mcfunction
- Asset/data/asset/tags/functions/mob/load.json
> :sparkles: AbstractAngel を作成

- Asset/data/asset/functions/mob/2000.abstract_angel/attack/.mcfunction
> [Mob2000] 天使抽象を修正

- Asset/data/asset/functions/artifact/0212.anti_materiel_rifle/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0212.anti_materiel_rifle/trigger/3.1.bullet.mcfunction
> :balance_scale: 対物ライフルの射程をナーフ

- Asset/data/asset/functions/artifact/1024.brave_rod/give/2.give.mcfunction
- 使用可能な信仰を変更
- 変な使用条件になっていたのを削除
> :balance_scale: [神器1024] ブレイブロッドの調整

- Asset/data/asset/functions/artifact/0920.dal_i_thalion/register.mcfunction
- Asset/data/asset/tags/functions/artifact/register.json
> :balance_scale: [神器920] ダル・イ・サリオンをregisterから破壊

- Asset/data/asset/functions/mob/0142.honey_soldier/attack/.mcfunction
> :recycle: [Mob142] ハニーソルジャーの修正

- Asset/data/asset/functions/artifact/0615.censored/trigger/3.4.execution.mcfunction
- Asset/data/asset/functions/artifact/0615.censored/trigger/3.5.execution_boss.mcfunction
- Asset/data/asset/functions/artifact/0615.censored/trigger/3.6.attack.mcfunction
- Asset/data/asset/functions/artifact/0615.censored/trigger/3.main.mcfunction
・DamageAPIへと変更
・ダメージ設定などをプレイヤーが実行するように(ここは思想)
・敵を消滅させる際にMobAPIのremoveを使うように
> :adhesive_bandage: [神器615] CENSOREDの修正

- Asset/data/asset/functions/artifact/1113.trick_and_treat/trigger/summon_pumpkin.mcfunction
- Asset/data/asset/functions/object/1057.giant_pumpkin/hit_entity/beginning_hit.mcfunction
- Asset/data/asset/functions/object/1057.giant_pumpkin/hit_entity/give_sweets/give.mcfunction
- Asset/data/asset/functions/object/1057.giant_pumpkin/hit_entity/high_speed_hit.mcfunction
- Asset/data/asset/functions/object/1057.giant_pumpkin/kill/.mcfunction
- Asset/data/asset/functions/object/1057.giant_pumpkin/register.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/register.mcfunction
- Asset/data/asset/functions/object/2031.giant_pumpkin/tick/high_speed_spin.mcfunction
> 🩹 [Object1057 & 2031] 巨大カボチャの演出を調整

- Asset/data/asset/functions/artifact/1098.mirror_piece_of_bygone_days/give/2.give.mcfunction
> 🩹 [神器1098] 在りし日の鏡片のLoreを調整

- Asset/data/asset/functions/artifact/0210.terra_blade/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0471.stone_cutter_chainsaw/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0899.flame_ring/trigger/add_modifier.mcfunction
- Asset/data/asset/functions/artifact/0899.flame_ring/trigger/dis_equip/main.mcfunction
- Asset/data/asset/functions/artifact/0976.brave_sword/give/2.give.mcfunction
Amountを0にするやつは一旦無視、渇望の剣は暫定的に無視している
> ⚖️ 一部神器からattributeのattack_damageを削除

- Asset/data/asset/functions/mob/0377.grey_guardian_v2/init/.mcfunction
- Asset/data/asset/functions/mob/0378.red_knight_v3/init/.mcfunction
> :alien: [Mob377-378] 新AJに対応

- Asset/data/asset/functions/artifact/0566.great_sage_helmet/trigger/fullset/damage/talk.mcfunction
- Asset/data/asset/functions/artifact/0566.great_sage_helmet/trigger/fullset/heal/.mcfunction
- Asset/data/asset/functions/artifact/0566.great_sage_helmet/trigger/fullset/heal/check.mcfunction
- Asset/data/asset/functions/artifact/0566.great_sage_helmet/trigger/fullset/heal/talk.mcfunction
- Asset/data/asset/functions/artifact/0566.great_sage_helmet/trigger/fullset/kill/talk.mcfunction
- Asset/data/asset/functions/artifact/0566.great_sage_helmet/trigger/fullset/kill/talk_genocide.mcfunction
- Asset/data/asset/tags/functions/artifact/heal.json
> 💬 [Artifact566-569] エリュサスのセリフを追加

- Asset/data/asset/functions/effect/0213.reflecting_sky/register.mcfunction
変更の意図としては、エフェクトの点滅が5秒スタートなので、それを対策したかった
> ⚖️ [Effect213] 映天の効果時間を延長

- Asset/data/asset/functions/effect/0253.purifying_indigo/register.mcfunction
- Asset/data/asset/functions/effect/0257.sprout/register.mcfunction
- Asset/data/asset/functions/effect/0259.virtual_image/register.mcfunction
> ⚖️ 一部エフェクトの解除要求Lvを3に

- Asset/data/asset/functions/object/1075.inferno_rush_arm/tick/hit.mcfunction
> :bug: [神器1075] インフェルノラッシュの攻撃対象が正しくない問題を修正

- Asset/data/asset/functions/mob/0055.hetukedah/tick/title.mcfunction
・…CBTまでに他のボスに付けるのは無理だし、となるとコイツについてるのはおかしいので。
> 🚸 [Mob55] ボス名のタイトル表示を無効化

- Asset/data/asset/functions/artifact/0816.fur_coad_of_firerat/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0816.fur_coad_of_firerat/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0816.fur_coad_of_firerat/trigger/dis_equip/main.mcfunction
- Asset/data/asset/functions/artifact/0817.dragons_neck_ball/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0817.dragons_neck_ball/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0817.dragons_neck_ball/trigger/dis_equip/main.mcfunction
- Asset/data/asset/functions/artifact/0818.bhuddas_bowl/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0818.bhuddas_bowl/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0818.bhuddas_bowl/trigger/dis_equip/main.mcfunction
- Asset/data/asset/functions/artifact/0819.swallows_cowry/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0819.swallows_cowry/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0819.swallows_cowry/trigger/dis_equip/main.mcfunction
さすがに耐性エフェクトは強すぎたのでattributeに変えた
> ⚖️ [神器 816-819] かぐや姫装備のバフ修正

- Asset/data/asset/functions/mob/0418.astro_zombie/attack/.mcfunction
- Asset/data/asset/functions/mob/0418.astro_zombie/register.mcfunction
- Asset/data/asset/functions/mob/0418.astro_zombie/summon/.mcfunction
- Asset/data/asset/functions/mob/0418.astro_zombie/summon/debug.mcfunction
- Asset/data/asset/functions/mob/0418.astro_zombie/tick/.mcfunction
- Asset/data/asset/functions/mob/0418.astro_zombie/tick/jump.mcfunction
- Asset/data/asset/functions/mob/alias/418/attack.mcfunction
- Asset/data/asset/functions/mob/alias/418/register.mcfunction
- Asset/data/asset/functions/mob/alias/418/summon.mcfunction
- Asset/data/asset/functions/mob/alias/418/tick.mcfunction
時間経過によって強化される普通のゾンビ
感覚としてはチェンソーゾンビの強化版
> 【Mob418】アストロゾンビ実装

- Asset/data/asset/functions/mob/0419.astro_drowned/attack/.mcfunction
- Asset/data/asset/functions/mob/0419.astro_drowned/register.mcfunction
- Asset/data/asset/functions/mob/0419.astro_drowned/summon/.mcfunction
- Asset/data/asset/functions/mob/0419.astro_drowned/summon/debug.mcfunction
- Asset/data/asset/functions/mob/alias/419/attack.mcfunction
- Asset/data/asset/functions/mob/alias/419/register.mcfunction
- Asset/data/asset/functions/mob/alias/419/summon.mcfunction
トライデントを投げてくる強化ドラウンド。
トライデントを命中させるとテレポートしてくる。
> :bento: [Mob419] アストロドラウンド実装

- Asset/data/asset/functions/mob/0424.icicle_leg/death/.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/hurt/.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/register.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/summon/.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/summon/debug.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/tick/.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/tick/icicle_rain/.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/tick/icicle_rain/shape.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/tick/icicle_rain/vfx.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/tick/jump.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/tick/stomp.mcfunction
- Asset/data/asset/functions/mob/alias/424/death.mcfunction
- Asset/data/asset/functions/mob/alias/424/hurt.mcfunction
- Asset/data/asset/functions/mob/alias/424/register.mcfunction
- Asset/data/asset/functions/mob/alias/424/summon.mcfunction
- Asset/data/asset/functions/mob/alias/424/tick.mcfunction
・氷結神社に「段差に強いヤツ」が必要らしいので作ったモブ。着地後の攻撃範囲が広い強敵！
> :bento: [Mob424] つらら脚を作成

- Asset/data/asset/loot_tables/mob/death/0077.chorus_zombie.json
> :alien: [Mob77] コーラスゾンビーのルートテーブルを修正

- Asset/data/asset/functions/artifact/0976.brave_sword/trigger/3.main.mcfunction
> 🐛 [神器976] ブレイブソードがオフハンドでコンボが繋がらない問題を修正

- Asset/data/asset/functions/artifact/0816.fur_coad_of_firerat/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/0816.fur_coad_of_firerat/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0817.dragons_neck_ball/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/0817.dragons_neck_ball/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0818.bhuddas_bowl/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/0818.bhuddas_bowl/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0819.swallows_cowry/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/0819.swallows_cowry/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/3.main.mcfunction
・スコアがリセットされていない問題を修正
・playsoundの種類がmasterだったこと、最少音量が1の音があったこと
> 🐛 [神器 816-820] かぐや姫装備のバグを修正

- Asset/data/asset/functions/artifact/0501.infinity/give/2.give.mcfunction
> ⚖️ [神器501] 無限増殖にCDを付与

- Asset/data/asset/functions/artifact/0647.thorn_armor/trigger/10.loop_process.mcfunction
- Asset/data/asset/functions/artifact/0724.oblivious_snow/trigger/fullset/attack.mcfunction
- Asset/data/asset/functions/artifact/0724.oblivious_snow/trigger/fullset/main.mcfunction
- Asset/data/asset/functions/artifact/0787.aurora_helm/trigger/fullset/main.mcfunction
> 💫 装備のフルセット時の演出を調整

- Asset/data/asset/functions/artifact/0958.whetstone_of_the_gods/trigger/check_progress.m.mcfunction
> 💬 [神器 958] 神々の砥石のメッセージ修正

- Asset/data/asset/functions/artifact/0143.nectar/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0144.hi_nectar/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0145.aure_nectar/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0146.mystica_nectar/give/2.give.mcfunction
- Asset/data/asset/functions/trader/5/register.mcfunction
ネクター使用回数調整
1->3
値段調整
5->10
10->20
24->48
48->96
（値段2倍）
> ネクターの使用回数と値段調整

- Asset/data/asset/functions/mob/0271.indomitable_warrior/summon/.mcfunction
> 🚸 [Mob0271] 不屈の剣士の中身をピグリンブルートに変更

- Asset/data/asset/functions/mob/0424.icicle_leg/init/.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/tick/.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/tick/icicle_rain/.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/tick/icicle_rain/damage.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/tick/stomp.mcfunction
- Asset/data/asset/functions/mob/alias/424/init.mcfunction
> ⚖️ [Mob0424] つらら脚のナーフ

- Asset/data/asset/functions/artifact/0672.aurora_blade/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0729.bloody_pride/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0731.mouse_feet/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0769.shaking_splash/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0801.red_secret_stone/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0840.honey_bee_stick/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0897.lightning_broach/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0907.rod_of_rain/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0950.residue_of_pumpkin/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0952.lunatic_rod/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0959.whirlwind_scabbard/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1051.blue_crystal_of_stardust/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1054.quick_charging_battery/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1056.one_drop_of_life/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1068.dream_of_burning_butterfly/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1069.sprout_of_dappled_sunlight/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1075.fairy_vial/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1078.pigeon_blood/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1079.allochromatic/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1080.allochromatic_empty/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1081.wandering_piece_of_dream/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1082.cursed_straw_doll/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1083.tablet_of_oracle/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1088.purifying_hydrangea/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1098.mirror_piece_of_bygone_days/give/2.give.mcfunction
> 💬 神器の冗長なLoreを調整

- Asset/data/asset/functions/artifact/0087.sheep_blessing/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0372.water_magic/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0372.water_magic/trigger/3.2.damage.mcfunction
- Asset/data/asset/functions/artifact/0383.i_scream_ice_cream/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0383.i_scream_ice_cream/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0738.voltage_striker/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0738.voltage_striker/trigger/bullet/hit.mcfunction
- Asset/data/asset/functions/artifact/0770.shaking_splash_empty/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0789.aurora_leggings/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0790.aurora_boots/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0796.log4shell/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0796.log4shell/trigger/3.2.hit.mcfunction
- Asset/data/asset/functions/artifact/0840.honey_bee_stick/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1027.fire_of_rebirth/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1027.fire_of_rebirth/trigger/summon.mcfunction
- Asset/data/asset/functions/artifact/1096.spirit_flute/give/2.give.mcfunction
> ⚖️ 神器のバランス調整

- Asset/data/asset/functions/artifact/0702.bright_lamp/trigger/3.main.mcfunction
> 🚸 [神器0702] 光照のランプの暗視の効果時間を調整

- Asset/data/asset/functions/mob/0049.ice_obstructor/attack/.mcfunction
> ⚖️ [Mob0049] 氷妨者の修正

- Asset/data/asset/functions/artifact/0816.fur_coad_of_firerat/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0816.fur_coad_of_firerat/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0817.dragons_neck_ball/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0817.dragons_neck_ball/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0818.bhuddas_bowl/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0818.bhuddas_bowl/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0819.swallows_cowry/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0819.swallows_cowry/trigger/3.main.mcfunction
> 💬 [神器816-819] かぐや姫装備の説明文追加

- Asset/data/asset/functions/artifact/0204.spelunker_shoes/trigger/3.main.mcfunction
> 🚸 [神器0204] スペランカーの靴の死亡処理を修正

- Asset/data/asset/functions/artifact/0927.lexiel_s_oath/trigger/4.critical_hit.mcfunction
> ⚖️ [神器0927] レクシエルの忠誠のクリティカルをBypassModifierへ

- Asset/data/asset/functions/mob/0237.lunatic_mage/register.mcfunction
- Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/elemental_confine/fire/hit.mcfunction
- Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/elemental_confine/in_activation.mcfunction
- Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/elemental_confine/water_jail/.mcfunction
- Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/elemental_confine/water_jail/vfx.mcfunction
- Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/magic/shoot_beam.mcfunction
- Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/magic_summon/water.mcfunction
> 🐛 [Mob0237] ルナティックメイジの修正

- Asset/data/asset/functions/mob/0227.frost_eye/hurt/.mcfunction
- Asset/data/asset/functions/mob/0227.frost_eye/hurt/debuff.mcfunction
- Asset/data/asset/functions/mob/0227.frost_eye/register.mcfunction
- Asset/data/asset/functions/mob/0227.frost_eye/tick/.mcfunction
- Asset/data/asset/functions/mob/0227.frost_eye/tick/attack.mcfunction
- Asset/data/asset/functions/mob/0227.frost_eye/tick/debuff.mcfunction
- Asset/data/asset/functions/mob/0228.frost_eye/register.mcfunction
> ⚖️ [Mob0227-228] フロストアイの調整

- Asset/data/asset/functions/artifact/0090.leather_armor_set/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0091.iron_armor_set/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0092.golden_armor_set/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0093.diamond_armor_set/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0094.netherite_armor_set/trigger/3.main.mcfunction
> ⚖️ [神器0090-0094] 簡易防具セットの防具を不可壊に

- Asset/data/asset/functions/artifact/1122.guardian_ironlump/trigger/removal.mcfunction
> 🐛 [神器1122] 守護者の鉄塊の修正

- Asset/data/asset/functions/mob/0175.queen_bee/tick/skill_needle/4.skill_needle_landing.mcfunction
> ⚖️ [Mob 175] クイーンビー 毒針のダメージ処理を修正

- Asset/data/asset/functions/mob/0373.gold_coffin/register.mcfunction
- Asset/data/asset/functions/mob/0374.gray_coffin/register.mcfunction
> 🚸 [Mob 373-374] 棺に名前を設定し忘れていたのを修正

- Asset/data/asset/functions/mob/0417.astro_skeleton/attack/.mcfunction
> [Mob0417] アストロスケルトンのナーフ

- Asset/data/asset/functions/mob/0059.jack_o_lantern/death/.mcfunction
- Asset/data/asset/functions/mob/0059.jack_o_lantern/remove/.mcfunction
- Asset/data/asset/functions/mob/0059.jack_o_lantern/summon/.mcfunction
- Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/.mcfunction
- Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/missile/shoot2.mcfunction
- Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/quiz/.mcfunction
- Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/quiz/kill_all_fake.mcfunction
- Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/quiz/quiz_fail/glowing.mcfunction
- Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/quiz/quiz_fail/summon_giant_pumpkin.mcfunction
- Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/quiz/random_move/.mcfunction
- Asset/data/asset/functions/mob/0224.fake_pumpkin/summon/.mcfunction
> [Mob0059] ジャック・オ・ランタンの修正

- Asset/data/asset/functions/mob/0418.astro_zombie/register.mcfunction
- Asset/data/asset/functions/mob/0418.astro_zombie/tick/.mcfunction
> :balance_scale: [Mob 418] アストロゾンビの修正

- Asset/data/asset/functions/mob/0176.killer_bee/load.mcfunction
- Asset/data/asset/functions/mob/0176.killer_bee/tick/.mcfunction
- Asset/data/asset/functions/mob/0176.killer_bee/tick/damage.mcfunction
- Asset/data/asset/functions/mob/0176.killer_bee/tick/remove.mcfunction
- Asset/data/asset/functions/mob/0186.ferocious_bee/load.mcfunction
- Asset/data/asset/functions/mob/0186.ferocious_bee/tick/.mcfunction
- Asset/data/asset/functions/mob/0186.ferocious_bee/tick/damage.mcfunction
- Asset/data/asset/tags/functions/mob/load.json
キラービーの処理を読んで、api:mob/removeしてないじゃん！凶暴なハチもそうだ！ってブランチ切って始めたら問題あるのキラービーだけだった
> :bug: [Mob 176, 186] キラービーと凶暴なハチの修正

- Asset/data/asset/functions/mob/0078.messenger_of_thunder/_index.d.mcfunction
- Asset/data/asset/functions/mob/0078.messenger_of_thunder/death/.mcfunction
- Asset/data/asset/functions/mob/0078.messenger_of_thunder/init/.mcfunction
- Asset/data/asset/functions/mob/0078.messenger_of_thunder/register.mcfunction
- Asset/data/asset/functions/mob/0078.messenger_of_thunder/remove/.mcfunction
- Asset/data/asset/functions/mob/0078.messenger_of_thunder/summon/.mcfunction
- Asset/data/asset/functions/mob/0078.messenger_of_thunder/tick/.mcfunction
- Asset/data/asset/functions/mob/0078.messenger_of_thunder/tick/skill/teleport_spread/spread.mcfunction
- Asset/data/asset/functions/mob/alias/78/remove.mcfunction
> [Mob0078] 雷鳴之使が出来る限り落下しないように

- Asset/data/asset/functions/mob/0376.convict_v2/tick/07.skill_axe7/alert.mcfunction
- Asset/data/asset/functions/mob/0376.convict_v2/tick/07.skill_axe7/main.mcfunction
- Asset/data/asset/functions/mob/0376.convict_v2/tick/07.skill_axe7/main_hard.mcfunction
> 断罪者の攻撃に円形予告を追加

- Asset/data/asset/tags/functions/artifact/register.json
> [神器0715-0718] 世界樹装備がregisterに入っていないのを修正

- Asset/data/asset/functions/effect/0029.poison/tick/m.mcfunction
- Asset/data/asset/functions/effect/0030.wither/tick/m.mcfunction
DurationはAmplifier:1のときに正常にダメージを与えられる最小値
> [Effect0029, 0030] 毒, 衰弱が正常にダメージを与えるように

- Asset/data/asset/functions/mob/0159.freeze_guardian/attack/.mcfunction
- Asset/data/asset/functions/mob/0159.freeze_guardian/register.mcfunction
> [Mob0159] 氷結ノ守護の修正

- Asset/data/asset/functions/object/2068.golden_watermelon/register.mcfunction
- Asset/data/asset/functions/object/2068.golden_watermelon/tick/1st_explode.mcfunction
> [Mob0076] ゴールデンスイカボマーの修正

- Asset/data/asset/functions/artifact/0236.health_exchanger/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/0236.health_exchanger/trigger/3.main.mcfunction
> ⚖️  Health Exchangerで交換する対象をランダムに1人に変更

- Asset/data/asset/functions/mob/0150.contamination/register.mcfunction
- Asset/data/asset/functions/mob/0151.recombined/attack/.mcfunction
- Asset/data/asset/functions/mob/0151.recombined/register.mcfunction
- Asset/data/asset/functions/mob/0152.desire/attack/.mcfunction
- Asset/data/asset/functions/mob/0152.desire/attack/absorption.mcfunction
- Asset/data/asset/functions/mob/0152.desire/attack/release.mcfunction
- Asset/data/asset/functions/mob/0152.desire/register.mcfunction
- Asset/data/asset/functions/mob/0153.domination/attack/.mcfunction
- Asset/data/asset/functions/mob/0153.domination/register.mcfunction
- Asset/data/asset/functions/mob/0154.ruin/attack/.mcfunction
- Asset/data/asset/functions/mob/0154.ruin/load.mcfunction
- Asset/data/asset/functions/mob/0154.ruin/register.mcfunction
- Asset/data/asset/functions/mob/0155.immorality/register.mcfunction
- Asset/data/asset/functions/mob/0156.infringement/register.mcfunction
- Asset/data/asset/tags/functions/mob/load.json
> エンドMob一括調整

- Asset/data/asset/functions/artifact/1033.thelema_of_blue_sea/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1033.thelema_of_blue_sea/trigger/4.persuit.mcfunction
- Asset/data/asset/functions/object/1039.thelema_persuit_entity/summon/debug.mcfunction
- Asset/data/asset/functions/object/1039.thelema_persuit_entity/tick/.mcfunction
- Asset/data/asset/functions/object/1039.thelema_persuit_entity/tick/set_summon_pos.mcfunction
- Asset/data/asset/functions/object/1039.thelema_persuit_entity/tick/summon_sword.mcfunction
- Asset/data/asset/functions/object/1040.thelema_persuit_sword/init/.mcfunction
- Asset/data/asset/functions/object/1040.thelema_persuit_sword/kill/.mcfunction
- Asset/data/asset/functions/object/1040.thelema_persuit_sword/load.mcfunction
- Asset/data/asset/tags/functions/object/load.json
・ExtendedCollisionに対してダメージが0.2倍に
・蒼波の剣の召喚密度を下げた
> [神器1033] 蒼海のテレームの調整

- Asset/data/asset/functions/object/2201.circle_announce/register.mcfunction
- Asset/data/asset/functions/object/2201.circle_announce/summon/.m.mcfunction
- Asset/data/asset/functions/object/2201.circle_announce/summon/.mcfunction
- Asset/data/asset/functions/object/2201.circle_announce/summon/debug.mcfunction
- Asset/data/asset/functions/object/2201.circle_announce/tick/.mcfunction
- Asset/data/asset/functions/object/2202.circle_announce_follow/register.mcfunction
- Asset/data/asset/functions/object/2202.circle_announce_follow/summon/debug.mcfunction
- Asset/data/asset/functions/object/2202.circle_announce_follow/tick/.mcfunction
- Asset/data/asset/functions/object/2202.circle_announce_follow/tick/move.m.mcfunction
- Asset/data/asset/functions/object/alias/2201/register.mcfunction
- Asset/data/asset/functions/object/alias/2201/summon.mcfunction
- Asset/data/asset/functions/object/alias/2201/tick.mcfunction
- Asset/data/asset/functions/object/alias/2202/register.mcfunction
- Asset/data/asset/functions/object/alias/2202/tick.mcfunction
> 🍱 [Object 2201, 2202] サークルエリア表示オブジェクトの追加

- Asset/data/asset/functions/artifact/0189.crystal_rod/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/1088.purifying_hydrangea/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/1098.mirror_piece_of_bygone_days/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/1141.bell_of_courage/trigger/debuff_clear.mcfunction
blocked by https://github.com/ProjectTSB/TheSkyBlessing/pull/1834
> :wastebasket: EffectAPIのArgument.IsSingleを削除

- Asset/data/asset/functions/mob/0259.shadow_stalker/register.mcfunction
> [Mob0259] シャドウストーカーのダメージが設定されていない問題を修正

- Asset/data/asset/functions/mob/0341.louvert/tick/animation/3_1_slash_start/.mcfunction
- Asset/data/asset/functions/object/2145.louvert_soul_blast/tick/.mcfunction
- Asset/data/asset/functions/object/2145.louvert_soul_blast/tick/warning/announce.mcfunction
> [Mob0341] ルヴェルトの一部攻撃にObjectでの予告を追加

- Asset/data/asset/functions/artifact/1037.grand_flame/give/2.give.mcfunction
> [神器1037] グランド・フレイムのLoreを調整

- Asset/data/asset/functions/effect/0620.ongaeshi/_/register.mcfunction
- Asset/data/asset/functions/effect/0620.ongaeshi/_/tick.mcfunction
- Asset/data/asset/functions/effect/0620.ongaeshi/register.mcfunction
- Asset/data/asset/functions/effect/0620.ongaeshi/tick/.mcfunction
- Asset/data/asset/functions/effect/0620.ongaeshi/tick/heal.mcfunction
- Asset/data/asset/functions/mob/0236.ksitigarbha/tick/ongaeshi.mcfunction
- Asset/data/asset/tags/functions/effect/register.json
- Asset/data/asset/tags/functions/effect/tick.json
> [Effect0620] 恩返しを作成

- Asset/data/asset/functions/artifact/0258.cat_dream_pillow/trigger/give_barrier.mcfunction
> :bug: [Artifact 258] 猫の夢見枕のバリアが小さい値へ上書きされるのを修正

- Asset/data/asset/functions/mob/0424.icicle_leg/tick/icicle_rain/.mcfunction
- Asset/data/asset/functions/mob/0424.icicle_leg/tick/stomp.mcfunction
> :children_crossing: [Mob 424] つらら脚がAoE中にY軸以外の移動をしないように

- Asset/data/asset/functions/artifact/0920.dal_i_thalion/give/2.give.mcfunction
> [神器0920] ダル・イ・サリオンのLoreを修正

- Asset/data/asset/functions/mob/0104.mad_scientist/tick/random_element_select.mcfunction
- Asset/data/asset/functions/mob/0104.mad_scientist/tick/summon/summon.mcfunction
- Asset/data/asset/functions/mob/0104.mad_scientist/tick/throw_potion.mcfunction
> 🐛 [Mob 104] マッドサイエンティストの投げるポーションの挙動が正しくないを修正

- Asset/data/asset/functions/artifact/0233.reversal/trigger/2.check_condition.mcfunction
> 🐛 [Artifact 233] 大逆転の体力割合の確認処理を修正

- Asset/data/asset/functions/mob/0187.flame_mage/register.mcfunction
- Asset/data/asset/functions/mob/0187.flame_mage/tick/.mcfunction
> 💫 [Mob 187] フレイムメイジの攻撃予告表示を改善

- Asset/data/asset/functions/mob/0021.demon_eye/load.mcfunction
- Asset/data/asset/functions/mob/0021.demon_eye/tick/.mcfunction
- Asset/data/asset/functions/mob/0021.demon_eye/tick/event/attack.mcfunction
- Asset/data/asset/functions/mob/0021.demon_eye/tick/rotater_tick.mcfunction
- Asset/data/asset/tags/functions/mob/load.json
> ♻️ [Mob 21] デーモンアイの攻撃処理と移動処理を改善

- Asset/data/asset/functions/mob/0106.mini_shulker/tick/.mcfunction
- Asset/data/asset/functions/mob/0106.mini_shulker/tick/attack/.mcfunction
- Asset/data/asset/functions/mob/0106.mini_shulker/tick/attack/reset.mcfunction
- Asset/data/asset/functions/mob/0106.mini_shulker/tick/select/.mcfunction
> :children_crossing: [Mob106] 敵をターゲットしているとき殻を開き続けるように

- Asset/data/asset/functions/mob/0058.divide_haze/0.load.mcfunction
- Asset/data/asset/functions/mob/0058.divide_haze/attack/.mcfunction
- Asset/data/asset/functions/mob/0058.divide_haze/hurt/.mcfunction
- Asset/data/asset/functions/mob/0058.divide_haze/tick/.mcfunction
- Asset/data/asset/functions/mob/0058.divide_haze/tick/divide.mcfunction
- Asset/data/asset/functions/mob/0058.divide_haze/tick/mob_count.mcfunction
- Asset/data/asset/functions/mob/0058.divide_haze/tick/wither.mcfunction
- Asset/data/asset/tags/functions/mob/load.json
> ♻️ [Mob 58] 増殖靄の実装を最新のものに変更

- Asset/data/asset/functions/artifact/0077.swords_of_waterfall_climbing/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0077.swords_of_waterfall_climbing/trigger/attack/dragon_strike/.mcfunction
- Asset/data/asset/functions/artifact/0077.swords_of_waterfall_climbing/trigger/attack/upper.mcfunction
- Asset/data/asset/functions/artifact/0077.swords_of_waterfall_climbing/trigger/attack/vfx.mcfunction
- Asset/data/asset/functions/effect/0190.fall_damage_immunity/_/end.mcfunction
- Asset/data/asset/functions/effect/0190.fall_damage_immunity/_/given.mcfunction
- Asset/data/asset/functions/effect/0190.fall_damage_immunity/_/register.mcfunction
- Asset/data/asset/functions/effect/0190.fall_damage_immunity/_/remove.mcfunction
- Asset/data/asset/functions/effect/0190.fall_damage_immunity/end/.mcfunction
- Asset/data/asset/functions/effect/0190.fall_damage_immunity/given/.mcfunction
- Asset/data/asset/functions/effect/0190.fall_damage_immunity/modifier/add.mcfunction
- Asset/data/asset/functions/effect/0190.fall_damage_immunity/modifier/remove.mcfunction
- Asset/data/asset/functions/effect/0190.fall_damage_immunity/register.mcfunction
- Asset/data/asset/functions/effect/0190.fall_damage_immunity/remove/.mcfunction
- Asset/data/asset/tags/functions/effect/end.json
- Asset/data/asset/tags/functions/effect/given.json
- Asset/data/asset/tags/functions/effect/register.json
- Asset/data/asset/tags/functions/effect/remove.json
> 🚸 [Artifact 77] 刀剣「滝登り」使用時に落下ダメージ無効化を付与するように

- Asset/data/asset/functions/artifact/0008.mysterious_tambourine/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0008.mysterious_tambourine/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0008.mysterious_tambourine/trigger/vfx.mcfunction
> ⚖️ [Artifact 8] 不思議なタンバリンの効果範囲を全プレイヤーに変更

- Asset/data/asset/functions/artifact/0840.honey_bee_stick/give/2.give.mcfunction
> :speech_balloon: [Artifact 840] ハニービーステッキのLoreを調整

- Asset/data/asset/functions/mob/0107.dark_ender/tick/.mcfunction
- Asset/data/asset/functions/mob/alias/107/tick.mcfunction
> :dizzy: [Mob 107] ダークエンダーに簡易的な演出を追加

- Asset/data/asset/functions/artifact/0003.humanity/trigger/heal.mcfunction
> :adhesive_bandage: [Artifact 3] 人間性の回復量が過剰に大きいのを修正

- Asset/data/asset/functions/artifact/0605.ambition/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0605.ambition/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0605.ambition/trigger/_index.d.mcfunction
- Asset/data/asset/functions/artifact/0605.ambition/trigger/vfx/.mcfunction
- Asset/data/asset/functions/artifact/0605.ambition/trigger/vfx/circle.mcfunction
- Asset/data/asset/functions/artifact/0605.ambition/trigger/vfx/recursive.mcfunction
> :dizzy: [Artifact 605] 下克上の演出を追加

- Asset/data/asset/functions/mob/0007.ectoplasm/hurt/.mcfunction
- Asset/data/asset/functions/mob/0007.ectoplasm/register.mcfunction
- Asset/data/asset/functions/mob/alias/7/hurt.mcfunction
> ⚖️ [Mob 7] エクトプラズムのステータス調整

- Asset/data/asset/functions/artifact/0207.life_is_transitory/register.mcfunction
- Asset/data/asset/tags/functions/artifact/register.json
> 🔥 [Artifact 207] 夢幻泡影がシャードから生成されないように

- Asset/data/asset/functions/artifact/0930.z_flag/give/2.give.mcfunction
システム側で補正を書くという話はあるけど、まだ先になりそうなので先に直しておく
> [Artifact0930] Z旗の修正

- Asset/data/asset/functions/artifact/1053.grimoire_of_purity/give/2.give.mcfunction
> [Artifact1053] 純化の呪書の使用可能信仰を調整

- Asset/data/asset/functions/mob/0056.thunder_trifler/attack/.mcfunction
- Asset/data/asset/functions/mob/0056.thunder_trifler/attack/mp_reduce.mcfunction
- Asset/data/asset/functions/mob/0056.thunder_trifler/hurt/.mcfunction
- Asset/data/asset/functions/mob/0056.thunder_trifler/hurt/teleport.mcfunction
- Asset/data/asset/functions/mob/0056.thunder_trifler/init/.mcfunction
- Asset/data/asset/functions/mob/0056.thunder_trifler/register.mcfunction
- Asset/data/asset/functions/mob/0083.thunder_trifler/register.mcfunction
- Asset/data/asset/functions/mob/alias/56/init.mcfunction
> [Mob0056, 0083] 雷弄者のナーフ

- Asset/data/asset/functions/artifact/0736.sailor_hat/trigger/3.main.mcfunction
> [Artifact0736] 水兵の帽子の魔法攻撃デバフが消えない問題を修正

- Asset/data/asset/functions/mob/0156.infringement/register.mcfunction
> ⚖️ [Mob 156] 侵害のノックバックを削除

- Asset/data/asset/functions/artifact/0822.sound_of_a_star/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0822.sound_of_a_star/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0822.sound_of_a_star/trigger/_index.d.mcfunction
- Asset/data/asset/functions/artifact/0822.sound_of_a_star/trigger/summon_star.m.mcfunction
> 🩹 [Artifact 822] 星の音の修正

- Asset/data/asset/functions/artifact/0932.equal_speed_charlie_london/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0932.equal_speed_charlie_london/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0932.equal_speed_charlie_london/trigger/dis_equip/main.mcfunction
> [Artifact0932] Equal Speed Charlie Londonの修正

- Asset/data/asset/functions/mob/0058.divide_haze/attack/.mcfunction
- Asset/data/asset/functions/mob/0058.divide_haze/register.mcfunction
> [Mob0058] 増殖靄の攻撃にDamageAPIを用いるように

- Asset/data/asset/functions/artifact/0971.laser_eye_helmet/shot/hit.mcfunction
> :bug: [Artifact 971] レーザーアイヘルメットの攻撃属性が正しくないのを修正

- Asset/data/asset/functions/artifact/1192.celestial_harmony/give/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/1192.celestial_harmony/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1192.celestial_harmony/register.mcfunction
- Asset/data/asset/functions/artifact/1192.celestial_harmony/trigger/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/1192.celestial_harmony/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/1192.celestial_harmony/trigger/3.main.mcfunction
- Asset/data/asset/functions/effect/0303.celestial_target/_/register.mcfunction
- Asset/data/asset/functions/effect/0303.celestial_target/_/tick.mcfunction
- Asset/data/asset/functions/effect/0303.celestial_target/register.mcfunction
- Asset/data/asset/functions/effect/0303.celestial_target/tick/.mcfunction
- Asset/data/asset/functions/effect/0303.celestial_target/tick/random_rotate/m.mcfunction
- Asset/data/asset/functions/effect/0303.celestial_target/tick/random_rotate/tp.m.mcfunction
- Asset/data/asset/functions/effect/0303.celestial_target/tick/summon_star.m.mcfunction
- Asset/data/asset/functions/object/1097.celestial_star/detect_hit_entity/.mcfunction
- Asset/data/asset/functions/object/1097.celestial_star/hit_entity/.mcfunction
- Asset/data/asset/functions/object/1097.celestial_star/register.mcfunction
- Asset/data/asset/functions/object/1097.celestial_star/summon/.mcfunction
- Asset/data/asset/functions/object/1097.celestial_star/summon/debug.mcfunction
- Asset/data/asset/functions/object/1097.celestial_star/summon/m.mcfunction
- Asset/data/asset/functions/object/1097.celestial_star/tick/.mcfunction
- Asset/data/asset/functions/object/alias/1097/detect_hit_entity.mcfunction
- Asset/data/asset/functions/object/alias/1097/hit_entity.mcfunction
- Asset/data/asset/functions/object/alias/1097/register.mcfunction
- Asset/data/asset/functions/object/alias/1097/summon.mcfunction
- Asset/data/asset/functions/object/alias/1097/tick.mcfunction
- Asset/data/asset/tags/functions/artifact/attack/melee.json
- Asset/data/asset/tags/functions/artifact/give.json
- Asset/data/asset/tags/functions/artifact/register.json
- Asset/data/asset/tags/functions/effect/register.json
- Asset/data/asset/tags/functions/effect/tick.json
> :sparkles: [神器1192] セレスティアル・ハーモニーを作成

- Asset/data/asset/functions/artifact/1200.alchemy_hammer/give/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/1200.alchemy_hammer/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1200.alchemy_hammer/register.mcfunction
- Asset/data/asset/functions/artifact/1200.alchemy_hammer/trigger/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/1200.alchemy_hammer/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/1200.alchemy_hammer/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/1200.alchemy_hammer/trigger/summon_laser.mcfunction
- Asset/data/asset/functions/object/1098.alchemy_laser/_index.d.mcfunction
- Asset/data/asset/functions/object/1098.alchemy_laser/init/.mcfunction
- Asset/data/asset/functions/object/1098.alchemy_laser/init/area.mcfunction
- Asset/data/asset/functions/object/1098.alchemy_laser/register.mcfunction
- Asset/data/asset/functions/object/1098.alchemy_laser/summon/.mcfunction
- Asset/data/asset/functions/object/1098.alchemy_laser/summon/debug.mcfunction
- Asset/data/asset/functions/object/1098.alchemy_laser/tick/.mcfunction
- Asset/data/asset/functions/object/1098.alchemy_laser/tick/shot.mcfunction
- Asset/data/asset/functions/object/alias/1098/init.mcfunction
- Asset/data/asset/functions/object/alias/1098/register.mcfunction
- Asset/data/asset/functions/object/alias/1098/summon.mcfunction
- Asset/data/asset/functions/object/alias/1098/tick.mcfunction
- Asset/data/asset/tags/functions/artifact/attack/melee.json
- Asset/data/asset/tags/functions/artifact/give.json
- Asset/data/asset/tags/functions/artifact/register.json
> ✨ [神器1200] アルケミーハンマーの実装

- Asset/data/asset/functions/mob/0056.thunder_trifler/attack/.mcfunction
- Asset/data/asset/functions/mob/0056.thunder_trifler/attack/mp_reduce.mcfunction
- Asset/data/asset/functions/mob/0056.thunder_trifler/register.mcfunction
> 🩹[Mob0056] 雷弄者の微修正

- Asset/data/asset/functions/artifact/0201.cowardly_soul/give/2.give.mcfunction
> [Artifact0201] 臆病者の魂の中身のアイテムを変更

- Asset/data/asset/functions/artifact/0088.fertility_hoe/give/2.give.mcfunction
> 💬 [Artifact0088] 豊穣の鍬の説明を修正

- Asset/data/asset/functions/artifact/0702.bright_lamp/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0702.bright_lamp/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0702.bright_lamp/trigger/_index.d.mcfunction
- Asset/data/asset/functions/artifact/0702.bright_lamp/trigger/vfx.mcfunction
CD調整に関しては前にいいんじゃね？みたいなことを言われたのできにしなくていいかも
> ⚖️ [Artifact 702] 光照のランプの効果の調整および EffectAsset への移行 & 処理の改善

- Asset/data/asset/functions/artifact/0383.i_scream_ice_cream/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0383.i_scream_ice_cream/trigger/message/place_froze.mcfunction
- Asset/data/asset/functions/artifact/0383.i_scream_ice_cream/trigger/message/puns.mcfunction
> ♻️ [Artifact 383] 氷はもうこーりごりの構造の改善

- Asset/data/asset/functions/artifact/0003.humanity/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/0003.humanity/trigger/nyaptov.mcfunction
> :children_crossing: [Artifact 3] ニャプトフ信仰のプレイヤーが人間性を使用した場合死ぬように

- Asset/data/asset/functions/mob/0416.ahssat/_index.d.mcfunction
- Asset/data/asset/functions/mob/0416.ahssat/death/.mcfunction
- Asset/data/asset/functions/mob/0416.ahssat/register.mcfunction
- Asset/data/asset/functions/mob/0427.ahssat_split/register.mcfunction
- Asset/data/asset/functions/mob/0427.ahssat_split/summon/debug.mcfunction
- Asset/data/asset/functions/mob/alias/427/register.mcfunction
> ♻️ [Mob 416] アサットの分裂処理を改善

- Asset/data/asset/functions/artifact/0022.amen_ra_rod/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0022.amen_ra_rod/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0022.amen_ra_rod/trigger/summon_1.mcfunction
- Asset/data/asset/functions/artifact/0022.amen_ra_rod/trigger/summon_2.mcfunction
- Asset/data/asset/functions/object/1103.light_ball/_index.d.mcfunction
- Asset/data/asset/functions/object/1103.light_ball/init/.mcfunction
- Asset/data/asset/functions/object/1103.light_ball/register.mcfunction
- Asset/data/asset/functions/object/1103.light_ball/summon/.mcfunction
- Asset/data/asset/functions/object/1103.light_ball/summon/debug.mcfunction
- Asset/data/asset/functions/object/1103.light_ball/tick/.mcfunction
- Asset/data/asset/functions/object/1103.light_ball/tick/kill.mcfunction
- Asset/data/asset/functions/object/1103.light_ball/tick/track.m.mcfunction
- Asset/data/asset/functions/object/alias/1103/init.mcfunction
- Asset/data/asset/functions/object/alias/1103/register.mcfunction
- Asset/data/asset/functions/object/alias/1103/summon.mcfunction
- Asset/data/asset/functions/object/alias/1103/tick.mcfunction
> ⚖️ [Artifact 22] アメン・ラーの杖のリワーク

- Asset/data/asset/functions/artifact/1193.firebrand/give/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/1193.firebrand/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1193.firebrand/register.mcfunction
- Asset/data/asset/functions/artifact/1193.firebrand/trigger/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/1193.firebrand/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/1193.firebrand/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/1193.firebrand/trigger/vfx.mcfunction
- Asset/data/asset/tags/functions/artifact/attack/melee.json
- Asset/data/asset/tags/functions/artifact/give.json
- Asset/data/asset/tags/functions/artifact/register.json
> ✨️ [Artifact1193] ファイアブランドを作成

- Asset/data/asset/functions/artifact/0172.icicle/give/2.give.mcfunction
> 🐛 [Artifact 172] つららの属性表記を修正

- Asset/data/asset/functions/artifact/0729.bloody_pride/give/2.give.mcfunction
> 💬 [Artifact 729] 血塗られた矜持の回復量を表示するように

- Asset/data/asset/functions/artifact/0441.awaited_opportunity/trigger/message/.mcfunction
- Asset/data/asset/functions/artifact/0441.awaited_opportunity/trigger/message/hardluck.mcfunction
- Asset/data/asset/functions/artifact/0441.awaited_opportunity/trigger/message/magazine_mark.mcfunction
- Asset/data/asset/functions/object/1105.magazine_mark/register.mcfunction
- Asset/data/asset/functions/object/1105.magazine_mark/summon/.mcfunction
- Asset/data/asset/functions/object/1105.magazine_mark/summon/debug.mcfunction
- Asset/data/asset/functions/object/1105.magazine_mark/summon/m.mcfunction
- Asset/data/asset/functions/object/1105.magazine_mark/tick/.mcfunction
- Asset/data/asset/functions/object/alias/1105/register.mcfunction
- Asset/data/asset/functions/object/alias/1105/summon.mcfunction
- Asset/data/asset/functions/object/alias/1105/tick.mcfunction
> ♻️ [Artifact 441] 待望の瞬間のマガジンマークの表示を ObjectAsset に移行

- Asset/data/asset/functions/artifact/0953.meteor_rain/trigger/3.main.mcfunction
- Asset/data/asset/functions/object/1079.meteor_rain_emitter/register.mcfunction
- Asset/data/asset/functions/object/1079.meteor_rain_emitter/tick/.mcfunction
- Asset/data/asset/functions/object/1079.meteor_rain_emitter/tick/summon_meteor.mcfunction
- Asset/data/asset/functions/object/1080.meteor_rain/detect_hit_block/.mcfunction
- Asset/data/asset/functions/object/1080.meteor_rain/detect_hit_block/check/with_target.m.mcfunction
- Asset/data/asset/functions/object/1080.meteor_rain/detect_hit_block/check/without_target.m.mcfunction
- Asset/data/asset/functions/object/1080.meteor_rain/detect_hit_block/check_target.m.mcfunction
- Asset/data/asset/functions/object/1080.meteor_rain/kill/.mcfunction
- Asset/data/asset/functions/object/1080.meteor_rain/register.mcfunction
> 🐛 [Artifact 953] メテオレインのターゲッティングの修正 および 対象がいない場合隕石が降らない問題の修正

- Asset/data/asset/functions/artifact/0190.amor_wand/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0190.amor_wand/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0191.horus_wand/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0191.horus_wand/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0192.falcios_wand/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0192.falcios_wand/trigger/3.main.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/_/end.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/_/given.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/_/re-given.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/_/register.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/_/remove.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/_/tick.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/end/.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/given/.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/load.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/re-given/.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/register.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/remove/.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/reset/.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/tick/.mcfunction
- Asset/data/asset/functions/effect/0301.soul_light/tick/heal.mcfunction
- Asset/data/asset/tags/functions/effect/end.json
- Asset/data/asset/tags/functions/effect/given.json
- Asset/data/asset/tags/functions/effect/load.json
- Asset/data/asset/tags/functions/effect/re-given.json
- Asset/data/asset/tags/functions/effect/register.json
- Asset/data/asset/tags/functions/effect/remove.json
- Asset/data/asset/tags/functions/effect/tick.json
Fix #820 
バランス調整班の監修アリ
ついでに再生バフをEffectへ移行した
> ⚖ [Artifact 190-192] アモール / ホルス / ファルシオスの杖の効果の調整

- Asset/data/asset/functions/artifact/0730.lake_reflecting_starry_sky/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0730.lake_reflecting_starry_sky/trigger/2.check_condition.mcfunction
> ⚖ [Artifact 730] 湖鏡映天の使用条件を撤廃

- Asset/data/asset/functions/artifact/0261.holy_symbol_lv.1/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0265.holy_symbol_lv.5/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0269.holy_symbol_lv.10/give/2.give.mcfunction
> :speech_balloon: [Artifact 261 265 269] ホーリーシンボルの効果の表記を修正

- Asset/data/asset/functions/artifact/1174.sanguis/register.mcfunction
> ⚖ [Artifact 1174] サングイスをLv3神器へ変更

- Asset/data/asset/functions/artifact/0672.aurora_blade/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0822.sound_of_a_star/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/1192.celestial_harmony/trigger/3.main.mcfunction
サンダーストームは #1077 でObject移行をしているため行わない
> ♻️ 神器のMP割合取得処理をAPIで行うように

- Asset/data/asset/functions/artifact/0355.barrel/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0529.safety_helmet/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0563.heartland/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1074.farothdal/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1119.call_maid/give/2.give.mcfunction
> 🐛 神器のgive実行時にFailed to parse componentエラーが発生しないように

- Asset/data/asset/functions/mob/1004.tultaria/tick/skill/thunder/random_thunder/thunder/place_marker.mcfunction
> 🐛 SpreadMarkerの全体定義修正によるエラーを修正 2

- Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/init/.mcfunction
- Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/register.mcfunction
- Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/weapons/storm_shadow_prepare.mcfunction
- 浅い入射角で巡航ミサイルが空中の指定座標をぐるぐる回る問題を修正
- ブロックに埋まった場合対空砲が暗くなる問題を修正
> [mob 213]Terrible Sonic Bomberのバグ修正

- Asset/data/asset/functions/mob/0220.vena_cana/attack/.mcfunction
- Asset/data/asset/functions/mob/0220.vena_cana/hurt/.mcfunction
- Asset/data/asset/functions/mob/0220.vena_cana/register.mcfunction
> ⚖ [Mob 220] 大静脈のナーフ

- Asset/data/asset/functions/mob/0219.aorta/register.mcfunction
> ⚖ [Mob 219] 大動脈のナーフ

- Asset/data/asset/functions/artifact/0600.xtal/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0600.xtal/trigger/5.slash.mcfunction
- Asset/data/asset/functions/artifact/0600.xtal/trigger/particle/particle_2.mcfunction
> ⚖ [Artifact 600] Xtalの攻撃対象を単体に変更

- Asset/data/asset/functions/artifact/1219.firesprint/give/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/1219.firesprint/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1219.firesprint/trigger/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/1219.firesprint/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/1219.firesprint/trigger/3.main.mcfunction
- Asset/data/asset/functions/effect/0313.firesprint/_/end.mcfunction
- Asset/data/asset/functions/effect/0313.firesprint/_/given.mcfunction
- Asset/data/asset/functions/effect/0313.firesprint/_/register.mcfunction
- Asset/data/asset/functions/effect/0313.firesprint/_/remove.mcfunction
- Asset/data/asset/functions/effect/0313.firesprint/_/tick.mcfunction
- Asset/data/asset/functions/effect/0313.firesprint/end/.mcfunction
- Asset/data/asset/functions/effect/0313.firesprint/given/.mcfunction
- Asset/data/asset/functions/effect/0313.firesprint/modfier/add.mcfunction
- Asset/data/asset/functions/effect/0313.firesprint/modfier/remove.mcfunction
- Asset/data/asset/functions/effect/0313.firesprint/register.mcfunction
- Asset/data/asset/functions/effect/0313.firesprint/remove/.mcfunction
- Asset/data/asset/functions/effect/0313.firesprint/tick/.mcfunction
- Asset/data/asset/tags/functions/artifact/click.carrot_on_a_stick.json
- Asset/data/asset/tags/functions/artifact/give.json
- Asset/data/asset/tags/functions/effect/end.json
- Asset/data/asset/tags/functions/effect/given.json
- Asset/data/asset/tags/functions/effect/register.json
- Asset/data/asset/tags/functions/effect/remove.json
- Asset/data/asset/tags/functions/effect/tick.json
> ✨️ [Artifact 301] 火走りを作成

- .vscode/settings.json
- Asset/data/asset/tags/functions/mob/enroll_pool.json
Related ProjectTSB/TheSkyBlessing#1871
> :alien: 暗所ペナルティによる mob の選定用のプールタグを追加

- Asset/data/asset/functions/artifact/1118.time_samsara/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1118.time_samsara/trigger/_index.d.mcfunction
- Asset/data/asset/functions/artifact/1118.time_samsara/trigger/summon.mcfunction
- Asset/data/asset/functions/object/1051.time_laser/summon/.mcfunction
- Asset/data/asset/functions/object/1051.time_laser/tick/.mcfunction
- Asset/data/asset/functions/object/1051.time_laser/tick/damage.mcfunction
- Asset/data/asset/functions/object/1051.time_laser/tick/loop.mcfunction
> ⚖ [Artifact 1118] 時廻りの強化

- Asset/data/asset/functions/artifact/1066.weight_stone/give/2.give.mcfunction
- Asset/data/asset/functions/effect/0218.heavy_weight/modifier/add.m.mcfunction
- Asset/data/asset/functions/effect/0218.heavy_weight/modifier/add.mcfunction
- Asset/data/asset/functions/effect/0218.heavy_weight/register.mcfunction
- Asset/data/asset/functions/effect/0218.heavy_weight/tick/.m.mcfunction
- Asset/data/asset/functions/effect/0218.heavy_weight/tick/.mcfunction
Fix #944 
ノックバック耐性 +0.2 -> +0.6
跳躍力低下を削除
> :balance_scale: [Artifact 1066] つけもの石の効果の調整

- Asset/data/asset/functions/artifact/0615.censored/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0615.censored/trigger/execution/boss.mcfunction
- Asset/data/asset/functions/artifact/0615.censored/trigger/execution/mob.mcfunction
> ⚖ [Artifact0615] CENSOREDの消滅効果発動時に周囲の敵へダメージを与えるように

- Asset/data/asset/functions/object/1107.crystal_dart/hit_block/.mcfunction
- Asset/data/asset/functions/object/1107.crystal_dart/register.mcfunction
> ⚖️ [Object 1107] クリスタルダートの射程を調整

- Asset/data/asset/functions/trader/4/register.mcfunction
> :balance_scale: [Trader 4] シャードの取引に攻略進捗条件を追加

- Asset/data/asset/functions/mob/1004.tultaria/tick/base_move/break/start.mcfunction
> ⚖[モブID 1004]トゥルタリアは眷属を倒されてダウンしている間は被ダメージが2倍になるようになった

- Asset/data/asset/functions/mob/0327.eclael/tick/app.1_4.select_skill_latter_attack_near.mcfunction
> :bug: [Mob 327] エクレールが正常にスキル選択できない問題を修正

- Asset/data/asset/functions/object/1094.aa_missile/tick/.mcfunction
- Asset/data/asset/functions/object/1094.aa_missile/tick/death_check.mcfunction
- Asset/data/asset/functions/object/1095.ag_missile/tick/.mcfunction
- Asset/data/asset/functions/object/1095.ag_missile/tick/death_check.mcfunction
> [神器1176] ターゲットが不在になったらオブジェクトが空中で静止するバグを修正

- Asset/data/asset/functions/mob/0077.chorus_zombie/register.mcfunction
> :balance_scale: [Mob 77] コーラスゾンビーの速度をナーフ

- Asset/data/asset/functions/object/2194.labyria_death/tick/kill.mcfunction
> ✨ [Mob 390] 異界のウサギ共がボスドロを落とすように

- Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/3.3.2.set_target.mcfunction
- Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/3.3.3.get_attack_level.mcfunction
- Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/3.3.3.set_attack_data.mcfunction
- Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/3.3.4.get_mp_heal.mcfunction
- Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/_index.d.mcfunction
- Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/check_block.mcfunction
- Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/check_block_recursive.mcfunction
- Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/search_target.mcfunction
- Asset/data/asset/functions/object/1067.jewel_rod_of_horai/tick/attack/damage.mcfunction
- Asset/data/asset/functions/object/1067.jewel_rod_of_horai/tick/attack/particle_0.mcfunction
- Asset/data/asset/functions/object/1067.jewel_rod_of_horai/tick/attack/particle_1.mcfunction
- Asset/data/asset/functions/object/1067.jewel_rod_of_horai/tick/attack/particle_2.mcfunction
- Asset/data/asset/functions/object/1067.jewel_rod_of_horai/tick/attack/particle_3.mcfunction
- 弱神器に変更
- 強化条件を装備しているから持っているに変更
- ターゲットの探索範囲を拡大
> :balance_scale: [Artifact 820] 蓬莱の玉の枝リワーク

- Asset/data/asset/functions/artifact/0464.lightning_exploit/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0464.lightning_exploit/trigger/1.trigger.mcfunction
- Asset/data/asset/functions/artifact/0464.lightning_exploit/trigger/2.check_condition.mcfunction
- Asset/data/asset/functions/artifact/0464.lightning_exploit/trigger/3.main.mcfunction
> 🐛 [Artifact 464] サンダーボルトエクスプロイトがオフハンドで使える問題を修正

- Asset/data/asset/functions/mob/0336.cherry_blossom_fairy/attack/summon_shower.mcfunction
- Asset/data/asset/functions/mob/0336.cherry_blossom_fairy/register.mcfunction
- Asset/data/asset/functions/mob/0337.cherry_blossom_fairy/register.mcfunction
> ⚖ [Mob 336, 337] 桜の精霊をナーフ

- Asset/data/asset/functions/artifact/0189.crystal_rod/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0189.crystal_rod/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0771.milk_pack/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0771.milk_pack/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0920.dal_i_thalion/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1088.purifying_hydrangea/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1088.purifying_hydrangea/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/1088.purifying_hydrangea/trigger/remove_debuff.mcfunction
- Asset/data/asset/functions/artifact/1098.mirror_piece_of_bygone_days/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1098.mirror_piece_of_bygone_days/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/1108.white_lily_of_priestess/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1108.white_lily_of_priestess/trigger/5.clear_debuff.mcfunction
- Asset/data/asset/functions/artifact/1111.rod_o_redeem/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1141.bell_of_courage/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1141.bell_of_courage/trigger/debuff_clear.mcfunction
Related #1206
Fix #366
Fix #715
> :balance_scale: 全デバフ解除系神器を調整

- Asset/data/asset/functions/effect/0614.prominence_curse/tick/damage.mcfunction
- Asset/data/asset/functions/effect/0615.wave_curse/tick/damage.mcfunction
- Asset/data/asset/functions/effect/0616.lightning_curse/tick/damage.mcfunction
- Asset/data/asset/functions/mob/0369.prominence_spellbook/register.mcfunction
- Asset/data/asset/functions/mob/0370.wave_spellbook/register.mcfunction
- Asset/data/asset/functions/mob/0371.lightning_spellbook/register.mcfunction
> ⚖ [Mob 369-371] 3色魔導書のダメージを調整

- Asset/data/asset/functions/artifact/0554.catastrophe/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0554.catastrophe/trigger/fullset/attack/2.check.mcfunction
- Asset/data/asset/functions/artifact/0554.catastrophe/trigger/fullset/attack/5.buff.mcfunction
- Asset/data/asset/functions/artifact/0554.catastrophe/trigger/fullset/hurt/3.damage.mcfunction
- Asset/data/asset/functions/artifact/0555.catastrophe/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0556.catastrophe/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0557.catastrophe/give/2.give.mcfunction
- Asset/data/asset/functions/effect/0263.chivalry_of_ruin/modifier/add.mcfunction
- Asset/data/asset/functions/effect/0263.chivalry_of_ruin/register.mcfunction
> ⚖ [Artifact 554-557] カタストロフィのバフの最大スタックを10に変更

- Asset/data/asset/functions/object/2088.patriot_launcher/_index.d.mcfunction
- Asset/data/asset/functions/object/2088.patriot_launcher/init/.mcfunction
- Asset/data/asset/functions/object/2088.patriot_launcher/summon/.mcfunction
> ♻️ [Object 2088] 対空砲のモデル召喚処理をInitに移行

- Asset/data/asset/functions/object/2141.louvert_soul_bomb/tick/.mcfunction
- Asset/data/asset/functions/object/2141.louvert_soul_bomb/tick/cast.mcfunction
- Asset/data/asset/functions/object/2141.louvert_soul_bomb/tick/countdown.mcfunction
- Asset/data/asset/functions/object/2141.louvert_soul_bomb/tick/process.mcfunction
- Asset/data/asset/functions/object/2141.louvert_soul_bomb/tick/vfx.mcfunction
- Asset/data/asset/functions/object/2141.louvert_soul_bomb/tick/warning/.mcfunction
> :balance_scale: ルヴェルトの爆弾が高難易度かつプレイヤーが範囲内の時に倍速するように

- Asset/data/asset/functions/artifact/0645.raimei_boots/trigger/dis_equip/main.mcfunction
> 🐛 [Artifact 645] 雷鳴の足部位の補正が正常に消えてない問題を修正

- Asset/data/asset/functions/effect/0017.slowness/register.mcfunction
- Asset/data/asset/functions/effect/0029.poison/register.mcfunction
- Asset/data/asset/functions/effect/0067.slowness/register.mcfunction
- Asset/data/asset/functions/effect/0125.levitation/register.mcfunction
- Asset/data/asset/functions/effect/0191.night_vision/register.mcfunction
- Asset/data/asset/functions/effect/0202.sheep_blessing/register.mcfunction
- Asset/data/asset/functions/effect/0210.fading_speed/register.mcfunction
- Asset/data/asset/functions/effect/0211.fading_speed/register.mcfunction
- Asset/data/asset/functions/effect/0213.reflecting_sky/register.mcfunction
- Asset/data/asset/functions/effect/0214.quick_charge/register.mcfunction
- Asset/data/asset/functions/effect/0253.purifying_indigo/register.mcfunction
- Asset/data/asset/functions/effect/0259.virtual_image/register.mcfunction
- Asset/data/asset/functions/effect/0260.life_steal/register.mcfunction
- Asset/data/asset/functions/effect/0264.soul_mate/register.mcfunction
- Asset/data/asset/functions/effect/0277.the_world/register.mcfunction
- Asset/data/asset/functions/effect/0278.time_shackles/register.mcfunction
- Asset/data/asset/functions/effect/0279.poison_of_vinderre/register.mcfunction
- Asset/data/asset/functions/effect/0303.celestial_target/register.mcfunction
- Asset/data/asset/functions/effect/0306.reactivearmor_lock/register.mcfunction
- Asset/data/asset/functions/effect/0308.healer_trance/register.mcfunction
- Asset/data/asset/functions/effect/0309.healer_trance/register.mcfunction
- Asset/data/asset/functions/effect/0314.quick_charge_mp/register.mcfunction
- Asset/data/asset/functions/effect/0603.domination/register.mcfunction
- Asset/data/asset/functions/effect/0612.infringement/register.mcfunction
- Asset/data/asset/functions/effect/0618.soaked/register.mcfunction
> 🐛 一部エフェクトの説明が配列でない問題を修正

- Asset/data/asset/functions/artifact/0019.scripture/trigger/3.main.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/_/end.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/_/given.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/_/register.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/_/tick.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/end/.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/end/failure.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/end/success.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/end/vfx.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/end/vfx2.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/given/.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/register.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/tick/.mcfunction
- Asset/data/asset/functions/effect/0324.scripture_gambling/tick/vfx.mcfunction
- Asset/data/asset/tags/functions/effect/end.json
- Asset/data/asset/tags/functions/effect/given.json
- Asset/data/asset/tags/functions/effect/register.json
- Asset/data/asset/tags/functions/effect/tick.json
> ⚖[Artifact19] 聖典をランダム発動に変更

- Asset/data/asset/functions/artifact/0369.fire_magic/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0372.water_magic/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0610.call_fish/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0928.ankh/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1076.death_snap/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1124.was/give/2.give.mcfunction
ルーモアも使用可能神器を緩和
アンク、ウアスの使用可能信仰がアンバランスな問題を解決
> ⚖️一部神器の使用可能信仰を変更

- Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/13_sc_warp/5.1.damage_slash.mcfunction
- Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/13_sc_warp/5.2.throw_scythe.mcfunction
- storageで定義したダメージが適用されていなかったのを修正
> [MOB 338] ルビエル鎌のダメージ修正

- Asset/data/asset/functions/artifact/0253.holy_barrier/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0253.holy_barrier/trigger/3.main.mcfunction
> ⚖ [Artifact 253] ホーリー・バリアが周囲の敵も巻き込むように

- Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/fire2/.mcfunction
- Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/fire2/line/.mcfunction
- Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/fire2/line/vfx.mcfunction
> 🚸 [Mob 237] ルナティックメイジの炎3way攻撃に予告を追加

- Asset/data/asset/functions/artifact/1017.cutlass_of_endless_silence/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1017.cutlass_of_endless_silence/trigger/slash/second.mcfunction
> 🐛 [Artifact1017] 攻撃範囲を修正、ついでに同時ヒットしないように

- Asset/data/asset/functions/mob/1004.tultaria/death/.mcfunction
- Asset/data/asset/functions/object/2056.tultaria_death/tick/drop.m.mcfunction
- Asset/data/asset/functions/object/2056.tultaria_death/tick/end.mcfunction
> 🚸 [Mob 1004] トゥルタリアのドロップ位置を召喚地点の少し上にするように

- Asset/data/asset/functions/mob/0411.behemoth/register.mcfunction
- Asset/data/asset/functions/mob/0412.tiamat/register.mcfunction
> [MOB 410]取り巻きのLore調整

- Asset/data/asset/functions/mob/0378.red_knight_v3/tick/90.tp/loop_tp.mcfunction
> 🚑 [mob378] 赤騎士のテレポートが再帰しかねない問題を修正

- Asset/data/asset/functions/mob/0059.jack_o_lantern/death/.mcfunction
- Asset/data/asset/functions/mob/0059.jack_o_lantern/kill_objects/.mcfunction
- Asset/data/asset/functions/mob/0059.jack_o_lantern/remove/.mcfunction
> 🐛 [Mob 59] ジャック・オ・ランタンがremove時にObjectを削除していない問題を修正

- Asset/data/asset/functions/object/1049.lexiel_rod_fireball/kill/deal_damage.m.mcfunction
> 🐛 [Artifact 1112] 誓いの杖の属性が正しくない問題を修正

- Asset/data/asset/functions/artifact/0985.ark_of_the_sanctuary/trigger/vfx/sound.mcfunction
> 🐛 [Artifact 985] Ark of the Sanctuaryの斬撃音が遠くから聞こえる問題を修正

- Asset/data/asset/functions/trader/2/register.mcfunction
Related ProjectTSB/TheSkyBlessing#2061
Blocked ProjectTSB/TheSkyBlessing#2060
> :children_crossing: 道具商人の取引内容を調整

- Asset/data/asset/functions/artifact/0087.sheep_blessing/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/1253.wool_shooter/trigger/3.main.mcfunction
> :bug: ウールシューター ･ 羊の加護が色付き羊毛を持っている時に消費なしで使用できる問題を修正

- Asset/data/asset/functions/object/1107.crystal_dart/detect_hit_block/.mcfunction
- Asset/data/asset/functions/object/1107.crystal_dart/hit_block/.mcfunction
- Asset/data/asset/functions/object/1107.crystal_dart/recursive/.mcfunction
> 🐛 [Object 1107] クリスタルダーツがブロックを貫通しやすい問題を修正

- Asset/data/asset/functions/mob/0104.mad_scientist/register.mcfunction
- Asset/data/asset/functions/object/2070.potion/tick/poison/give.mcfunction
- Asset/data/asset/functions/object/2070.potion/tick/poison/tick.mcfunction
> ⚖ [Mob 104] マッドサイエンティストの毒のスタックを調整 & 毒を毎tick付与しないように

- Asset/data/asset/functions/effect/0297.life_is_transitory/_/end.mcfunction
- Asset/data/asset/functions/effect/0297.life_is_transitory/end/.mcfunction
- Asset/data/asset/functions/effect/0297.life_is_transitory/modifier/remove.mcfunction
- Asset/data/asset/tags/functions/effect/end.json
- Asset/data/asset/tags/functions/effect/given.json
> :bug: [Effect 297] 夢幻泡影の装備時に体力が減少しない問題を修正

- Asset/data/asset/functions/object/2064.black_penalty_bullet/tick/cast/damage.mcfunction
> 🐛 [Mob 390] 異界のウサギ共のペナルティのデスログが正常でない問題を修正

- Asset/LICENSE
- LICENSE
- README.md
Asset は今まで通り MIT で、scripts とかその他のディレクトリを CC0 として明示する目的
> :page_facing_up: ライセンス周りをいい感じにする

- Asset/data/asset/functions/artifact/1262.honey_bee_stiring/trigger/3.main.mcfunction
> 🐛 [Artifact 1262] ハニービースティリングが矢を2本消費する問題を修正

- Asset/data/asset/functions/object/1054.ride_missile/kill/.mcfunction
- Asset/data/asset/functions/object/1054.ride_missile/tick/.mcfunction
> 🐛 [Artifact 1123] ライドミサイルが破壊不可能エリアで飛行できる問題を修正

- Asset/data/asset/functions/artifact/0606.traffic_sign/give/2.give.mcfunction
> 💬 [Artifact 606] 交通標識の説明を調整

- Asset/data/asset/functions/mob/0154.ruin/attack/.mcfunction
- Asset/data/asset/functions/mob/0154.ruin/register.mcfunction
- Asset/data/asset/functions/mob/0154.ruin/tick/.mcfunction
- Asset/data/asset/functions/mob/0154.ruin/tick/4.madness.mcfunction
- Asset/data/asset/functions/mob/0154.ruin/tick/death.mcfunction
- Asset/data/asset/functions/mob/0154.ruin/tick/madness.mcfunction
- Asset/data/asset/functions/mob/0154.ruin/tick/ready.mcfunction
・形態変化後の耐性エフェクトを撤廃
・ダメージが難易度によって変動する仕様を撤廃
・ダメージをregisterで定義するように
> ⚖ [Mob 154] 破滅の調整

- Asset/data/asset/functions/object/1144.hekireki_thunder/tick/thunder.mcfunction
Fix #1529
$UserIDがリセットされてないのも直した
> ⚖ [Artifact 1061] 霹靂の十字の雷のダメージ範囲を拡大 

- Asset/data/asset/functions/artifact/0071.ariadne_thread/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0164.blessing_boots/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0165.blessing_leggings/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0166.blessing_armor/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0167.blessing_helmet/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0273.tonbo_gaeri/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0437.only_the_crabs_know/trigger/taste/heavenly_feeling.mcfunction
- Asset/data/asset/functions/artifact/0741.abyss_insurance_card/trigger/3.main.mcfunction
> 🐛 初期地点に帰還する神器がディメンションを超えた際に落下死しうる問題を修正

- Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/quiz/quiz_fail/glow.mcfunction
- Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/quiz/random_move/move.mcfunction
- Asset/data/asset/functions/mob/0123.lexiel_v3/tick/common/thunder/main.mcfunction
- Asset/data/asset/functions/mob/0219.aorta/hurt/check_health.mcfunction
- Asset/data/asset/functions/mob/0437.lawless_iron_doll/tick/base_move/.mcfunction
- Asset/data/asset/functions/mob/0437.lawless_iron_doll/tick/base_move/skill/horizontal_slash_shot/alert/.mcfunction
- Asset/data/asset/functions/mob/0437.lawless_iron_doll/tick/base_move/skill/horizontal_slash_shot/slash_shot/.mcfunction
- Asset/data/asset/functions/mob/0437.lawless_iron_doll/tick/base_move/skill/shockwave/alert/.mcfunction
- Asset/data/asset/functions/mob/0437.lawless_iron_doll/tick/base_move/skill_select/cycle_reset/.mcfunction
- Asset/data/asset/functions/object/2103.lexiel_explode/init/.mcfunction
- Asset/data/asset/functions/object/2103.lexiel_explode/tick/.mcfunction
> 🐛 一部Mobがover_diffucultyで正常に動作しない問題を修正

- Asset/data/asset/functions/artifact/0725.oblivious_snow/give/2.give.mcfunction
> 🐛 [Artifact 725] 白霜に覆われた心にEffectIDが登録されていない問題を修正

- Asset/data/asset/functions/artifact/1024.brave_rod/trigger/combo/laser_damage.mcfunction
Fix #1539
本当はエフェクト使ったほうだ良いんだろうな~~~とか思いつつッて感じ
> 🐛 [Artifact 1024] ブレイブロッドのMP回復量が実際の数値と一致していない問題を修正

- Asset/data/asset/functions/artifact/1057.great_demon_head/tick/3.main.mcfunction
> :bug: [Artifact 1057-1060] 豪鬼の鎧のフルセット効果発動時に着脱音がする問題を修正

- Asset/data/asset/functions/artifact/1207.quadrainbow_icequality/trigger/2.check_condition.mcfunction
> :bug: [Artifact 1207] 使用条件と使用不可メッセージの式が一致しないのを修正

- Asset/data/asset/functions/artifact/0008.mysterious_tambourine/register.mcfunction
- Asset/data/asset/functions/artifact/0033.magic_shield/register.mcfunction
- Asset/data/asset/functions/artifact/0456.potion_of_stalling_power/register.mcfunction
> :bug: ルールに沿っていない一部のカラーシャード排出を修正

- Asset/data/asset/functions/trader/14/register.mcfunction
> :balance_scale: カラーシャード商人の進行度制限を撤廃

- Asset/data/asset/functions/artifact/1183.cosmo_site/give/2.give.mcfunction
> :bug: コズモサイトのダメージ表記が間違っているのを修正

- Asset/data/asset/functions/mob/0391.axia_first/ai/animation/100_0_opening/.mcfunction
- Asset/data/asset/functions/mob/0391.axia_first/init/.mcfunction
> 🐛 [Mob 0391] アキシャが召喚時にTポーズになるバグを暫定的に修正

- Asset/data/asset/functions/mob/0053.executioners/hurt/.mcfunction
- Asset/data/asset/functions/mob/0056.thunder_trifler/hurt/.mcfunction
- Asset/data/asset/functions/mob/0058.divide_haze/hurt/.mcfunction
- Asset/data/asset/functions/mob/0089.decapitation/hurt/.mcfunction
- Asset/data/asset/functions/mob/0106.mini_shulker/hurt/.mcfunction
- Asset/data/asset/functions/mob/0114.jewel_hunter/hurt/.mcfunction
- Asset/data/asset/functions/mob/0124.skull_harpy/hurt/.mcfunction
- Asset/data/asset/functions/mob/0147.prismarine_slayer/hurt/.mcfunction
- Asset/data/asset/functions/mob/0150.contamination/hurt/.mcfunction
- Asset/data/asset/functions/mob/0171.lumberjack_of_blue_forest/hurt/.mcfunction
- Asset/data/asset/functions/mob/0182.skull_raven/hurt/.mcfunction
- Asset/data/asset/functions/mob/0219.aorta/hurt/.mcfunction
- Asset/data/asset/functions/mob/0257.distortion_spellbook/hurt/.mcfunction
- Asset/data/asset/functions/mob/0259.shadow_stalker/hurt/.mcfunction
- Asset/data/asset/functions/mob/0280.the_desire_for_burning/hurt/.mcfunction
- Asset/data/asset/functions/mob/0327.eclael/hurt/.mcfunction
- Asset/data/asset/functions/mob/0330.aurora_reaper/hurt/.mcfunction
- Asset/data/asset/functions/mob/0339.twins_sapphiel/hurt/.mcfunction
- Asset/data/asset/functions/mob/0340.twins_rubiel/hurt/.mcfunction
- Asset/data/asset/functions/mob/0341.louvert/hurt/.mcfunction
- Asset/data/asset/functions/mob/0391.axia_first/hurt/.mcfunction
- Asset/data/asset/functions/mob/0392.ecual_first/hurt/.mcfunction
- Asset/data/asset/functions/mob/0393.labyria_first/hurt/.mcfunction
Fix ProjectTSB/TheSkyBlessing#2085
Fix #1432
> :children_crossing: Mob の一部 Hurt 処理が DoT で発動しないように

- Asset/data/asset/functions/effect/0025.levitation/_/end.mcfunction
- Asset/data/asset/functions/effect/0025.levitation/_/register.mcfunction
- Asset/data/asset/functions/effect/0025.levitation/_/remove.mcfunction
- Asset/data/asset/functions/effect/0025.levitation/_/tick.mcfunction
- Asset/data/asset/functions/effect/0025.levitation/end/.mcfunction
- Asset/data/asset/functions/effect/0025.levitation/register.mcfunction
- Asset/data/asset/functions/effect/0025.levitation/remove/.mcfunction
- Asset/data/asset/functions/effect/0025.levitation/tick/.mcfunction
- Asset/data/asset/functions/effect/0025.levitation/tick/m.mcfunction
- Asset/data/asset/functions/mob/0263.shulker_bullet/explode/.mcfunction
- Asset/data/asset/tags/functions/effect/end.json
- Asset/data/asset/tags/functions/effect/register.json
- Asset/data/asset/tags/functions/effect/remove.json
- Asset/data/asset/tags/functions/effect/tick.json
> ⚖ [Mob 106] ミニシュルカーの付与する浮遊をLv1に

- Asset/data/asset/functions/artifact/0820.jewel_rod_of_horai/trigger/3.main.mcfunction
- Asset/data/asset/functions/object/1067.jewel_rod_of_horai/tick/attack/damage.mcfunction
> 🐛 [Artifact 820] 蓬莱の玉の枝の2発目以降でMP回復がない問題を修正

- Asset/data/asset/functions/mob/0372.tutankhamen/register.mcfunction
- Asset/data/asset/functions/mob/0391.axia_first/register.mcfunction
- Asset/data/asset/functions/mob/0392.ecual_first/register.mcfunction
- Asset/data/asset/functions/mob/0393.labyria_first/ai/animation/14_0_sw_thunder_spear/elect/select.mcfunction
- Asset/data/asset/functions/mob/0393.labyria_first/register.mcfunction
- Asset/data/asset/functions/mob/0397.crystal_turret/register.mcfunction
- Asset/data/asset/functions/mob/0398.crystal_healer/register.mcfunction
- Asset/data/asset/functions/mob/0399.void_spellbook/register.mcfunction
- Asset/data/asset/functions/mob/0400.explosion_spellbook/ai/explode/.mcfunction
- Asset/data/asset/functions/mob/0400.explosion_spellbook/register.mcfunction
- Asset/data/asset/functions/mob/0410.heiloang/register.mcfunction
- Asset/data/asset/functions/mob/0411.behemoth/register.mcfunction
- Asset/data/asset/functions/mob/0412.tiamat/register.mcfunction
- Asset/data/asset/functions/object/2012.thunder_spear/tick/elect/hard_cast.mcfunction
- Asset/data/asset/functions/object/2012.thunder_spear/tick/elect/normal_cast.mcfunction
- Asset/data/asset/functions/object/2012.thunder_spear/tick/start/cast.mcfunction
- Asset/data/asset/functions/object/2016.axia_critical/tick/cast.mcfunction
- Asset/data/asset/functions/object/2017.ecual_water_magic/tick/cast.mcfunction
- Asset/data/asset/functions/object/2022.ecual_critical/tick/cast.mcfunction
> ⚖️ 天使のステータス調整

- Asset/data/asset/functions/artifact/0212.anti_materiel_rifle/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0607.u_and_w_06/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0758.sina_tk/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1079.allochromatic/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/1089.antimatter_gatling_rifle/give/2.give.mcfunction
- ID212 対物ライフル
- ID607 U&W-06
- ID758 Sina-TK
- ID1079 アロクロマティック
- ID1089 反物質回転式多銃身機関銃
> :balance_scale: ルーモアが使用可能な神器を追加

- Asset/data/asset/functions/trader/3/register.mcfunction
> :bug: 醸造商人が空気を売っているのを修正

- Asset/data/asset/functions/artifact/0002.blessing/trigger/3.main.mcfunction
- Asset/data/asset/functions/artifact/0002.blessing/trigger/on_trigger.mcfunction
- Asset/data/asset/functions/artifact/0002.blessing/trigger/show_trigger_chat.mcfunction
> :bug: 手動で triggerコマンドを実行することで上限を超えてステータスを振れるのを修正

- Asset/data/asset/functions/mob/0124.skull_harpy/attack/.mcfunction
- Asset/data/asset/functions/mob/0124.skull_harpy/hurt/.mcfunction
- Asset/data/asset/functions/mob/0124.skull_harpy/register.mcfunction
- Asset/data/asset/functions/mob/0182.skull_raven/attack/.mcfunction
- Asset/data/asset/functions/mob/0182.skull_raven/hurt/.mcfunction
- Asset/data/asset/functions/mob/0182.skull_raven/register.mcfunction
ついでにダメージ定義をregisterでやるようにしている
ここまできたら継承してもいいんじゃねって気持ちもあるけど、いまいちやる気がわかないのでやってない
> 🚸 [Mob 124, 182] スカルハーピィ & スカルレイブンが、プレイヤーから離れている場合に逃避行動をとらないように

- Asset/data/asset/functions/object/1146.rubeus_resonance/tick/attack/do.mcfunction
> :bug: [Artifact 1079] アロクロマティックの追撃がプレイヤーを巻き込むことがある問題を修正

- Asset/data/asset/functions/effect/0029.poison/register.mcfunction
- Asset/data/asset/functions/effect/0030.wither/register.mcfunction
> 💭 [Effect 29, 30] 毒, 衰弱の説明を調整

- Asset/data/asset/functions/mob/0261.laser_eye_mk2/tick/.mcfunction
> 🐛 [Mob 261] レーザーアイMk-Ⅱがすぐ後ろに壁があると攻撃しない問題を修正

- Asset/data/asset/functions/artifact/0911.reactive_armor_head/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0912.reactive_armor_chest/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0913.reactive_armor_legs/give/2.give.mcfunction
- Asset/data/asset/functions/artifact/0914.reactive_armor_feet/give/2.give.mcfunction
> 🩹 [Artifact 911-914] リアクティブアーマーの発動条件についての記載を削除

- Asset/data/asset/functions/mob/0046.clock_of_despair/remove/.mcfunction
- Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/11_oclock.mcfunction
> 🐛 [Mob 46] 絶望の時計がメイジを適切に削除できていない問題を修正

- Asset/data/asset/functions/artifact/1217.archer_fish/trigger/search_target.mcfunction
> 🐛 [Artifact 1217] アーチャー・フィッシュのターゲット探索処理が正常に機能していない問題を修正

- Asset/data/asset/functions/object/1111.archer_fish/recursive/.mcfunction
- Asset/data/asset/functions/object/1111.archer_fish/summon/m.mcfunction
> 🐛 [Artifact 1217] アーチャー・フィッシュの魚の判定が見た目と一致していない問題を修正

- Asset/data/asset/functions/artifact/0981.soulfire_burst/trigger/summon_object.mcfunction
> 🐛 [Artifact 981] ソウルファイアシーカーが射程範囲外の敵を狙ってしまう問題を修正
