ProjectTSB/Asset

Asset/data/asset/functions/artifact/0672.aurora_blade/give/2.give.mcfunction, Asset/data/asset/functions/artifact/0672.aurora_blade/trigger/3.main.mcfunction
・Loreの修正
・ダメージ+50％の条件を"天使を攻撃"から"現在MPが70％以上"に変更
・その他諸々の細かい修正
=> [神器672] オーロラブレードの修正

Asset/data/asset/functions/artifact/0959.whirlwind_scabbard/give/2.give.mcfunction, Asset/data/asset/functions/artifact/0959.whirlwind_scabbard/trigger/1.trigger.mcfunction, Asset/data/asset/functions/artifact/0959.whirlwind_scabbard/trigger/2.check_condition.mcfunction, Asset/data/asset/functions/artifact/0959.whirlwind_scabbard/trigger/3.main.mcfunction
・対象スロットをhotbarからoffhandに
・複数所持による効果向上を削除
・ノックバック効果を強化
=> [神器959] 旋風の鞘の効果を変更

Asset/data/asset/functions/mob/0182.skull_raven/summon/2.summon.mcfunction
ノーマル以上でパンチ弓、イージーだと普通の弓になっている
てかいつ浮遊付与がハード以上限定になったの？
=> ⚖️ [Mob182] スカルレイブンの難易度対応

Asset/data/asset/functions/object/0001.abstract_projectile/init/.mcfunction, Asset/data/asset/functions/object/0001.abstract_projectile/load.mcfunction, Asset/data/asset/functions/object/0001.abstract_projectile/summon/debug.mcfunction, Asset/data/asset/functions/object/0001.abstract_projectile/tick/move.m.mcfunction, Asset/data/asset/functions/object/0001.abstract_projectile/tick/recursive.mcfunction
0.5刻みだと早すぎるとき用。
- RangeやSpeedを指定するのと同じように、MovePerTickに1tickに進む距離を指定できるようにしました。
- 低弾速の弾を作るのに便利だと思います。
=> 抽象発射体が1tickに進む距離を指定できるようにした

Asset/data/asset/functions/artifact/0002.blessing/give/1.trigger.mcfunction, Asset/data/asset/functions/artifact/0002.blessing/give/2.give.mcfunction, Asset/data/asset/functions/artifact/0002.blessing/give/get_random_name.mcfunction, Asset/data/asset/functions/artifact/0002.blessing/trigger/0.load.mcfunction, Asset/data/asset/functions/artifact/0002.blessing/trigger/1.trigger.mcfunction, Asset/data/asset/functions/artifact/0002.blessing/trigger/2.check_condition.mcfunction, Asset/data/asset/functions/artifact/0002.blessing/trigger/3.main.mcfunction, Asset/data/asset/functions/artifact/0002.blessing/trigger/_index.d.mcfunction, Asset/data/asset/functions/artifact/0002.blessing/trigger/listener.mcfunction, Asset/data/asset/functions/artifact/0002.blessing/trigger/on_trigger.mcfunction, Asset/data/asset/functions/artifact/0002.blessing/trigger/rejoin_process.mcfunction, Asset/data/asset/functions/artifact/0002.blessing/trigger/show_trigger_chat.mcfunction, Asset/data/asset/tags/functions/artifact/click.carrot_on_a_stick.json, Asset/data/asset/tags/functions/artifact/give.json, Asset/data/asset/tags/functions/artifact/load.json, Asset/data/asset/tags/functions/rejoin.json
=> :truck: [神器2] 祝福をAssetリポジトリに迎え入れる

Asset/data/asset/functions/artifact/1106.rainbow_candy/give/2.give.mcfunction, Asset/data/asset/functions/artifact/1106.rainbow_candy/register.mcfunction, Asset/data/asset/tags/functions/artifact/register.json
トリック・アンド・トリートでgiveされるように仕様を変えるため
・加工機から出ないように
・使用回数を減らした
=> :balance_scale: [神器1106] 虹色キャンディの調整

Asset/data/asset/functions/mob/0423.edge_mage/attack/.mcfunction, Asset/data/asset/functions/mob/0423.edge_mage/attack/fire.mcfunction, Asset/data/asset/functions/mob/0423.edge_mage/attack/thunder.mcfunction, Asset/data/asset/functions/mob/0423.edge_mage/attack/water.mcfunction, Asset/data/asset/functions/mob/0423.edge_mage/death/.mcfunction, Asset/data/asset/functions/mob/0423.edge_mage/hurt/.mcfunction, Asset/data/asset/functions/mob/0423.edge_mage/register.mcfunction, Asset/data/asset/functions/mob/0423.edge_mage/summon/.mcfunction, Asset/data/asset/functions/mob/0423.edge_mage/tick/.mcfunction, Asset/data/asset/functions/mob/alias/423/attack.mcfunction, Asset/data/asset/functions/mob/alias/423/death.mcfunction, Asset/data/asset/functions/mob/alias/423/hurt.mcfunction, Asset/data/asset/functions/mob/alias/423/register.mcfunction, Asset/data/asset/functions/mob/alias/423/summon.mcfunction, Asset/data/asset/functions/mob/alias/423/tick.mcfunction
メイジ島に出てくる敵、ほとんど全員が特殊攻撃持ちで忙しね～…と感じたので、にぎやかし担当として作りました。いつものメイジをエリート枠とするなら、コイツらはそれといっしょに現れるザコです。
近接タイプですが何気にメイジ系と耐性が同じで、強力な魔法耐性を持ちますが、物理攻撃に弱いです。
他の島にも出せそうですが、妙な耐性と攻撃属性を持っているのがネックになりそう。
=> 🍱 [Mob423] エッジメイジを作成

Asset/data/asset/functions/mob/0420.astro_blaze/attack/.mcfunction, Asset/data/asset/functions/mob/0420.astro_blaze/register.mcfunction, Asset/data/asset/functions/mob/0420.astro_blaze/summon/.mcfunction, Asset/data/asset/functions/mob/0420.astro_blaze/summon/debug.mcfunction, Asset/data/asset/functions/mob/0420.astro_blaze/tick/.mcfunction, Asset/data/asset/functions/mob/0420.astro_blaze/tick/fire.mcfunction, Asset/data/asset/functions/mob/0420.astro_blaze/tick/jump.mcfunction, Asset/data/asset/functions/mob/0420.astro_blaze/tick/pre_bullet.mcfunction, Asset/data/asset/functions/mob/0420.astro_blaze/tick/summon.mcfunction, Asset/data/asset/functions/mob/alias/420/attack.mcfunction, Asset/data/asset/functions/mob/alias/420/register.mcfunction, Asset/data/asset/functions/mob/alias/420/summon.mcfunction, Asset/data/asset/functions/mob/alias/420/tick.mcfunction, Asset/data/asset/functions/object/2171.astro_blaze_bullet/hit_entity/.mcfunction, Asset/data/asset/functions/object/2171.astro_blaze_bullet/init/.mcfunction, Asset/data/asset/functions/object/2171.astro_blaze_bullet/register.mcfunction, Asset/data/asset/functions/object/2171.astro_blaze_bullet/summon/.mcfunction, Asset/data/asset/functions/object/2171.astro_blaze_bullet/summon/debug.mcfunction, Asset/data/asset/functions/object/2171.astro_blaze_bullet/tick/.mcfunction, Asset/data/asset/functions/object/alias/2171/hit_entity.mcfunction, Asset/data/asset/functions/object/alias/2171/init.mcfunction, Asset/data/asset/functions/object/alias/2171/register.mcfunction, Asset/data/asset/functions/object/alias/2171/summon.mcfunction, Asset/data/asset/functions/object/alias/2171/tick.mcfunction
大量の弾幕を撃ってくるブレイズ。
弾幕を撃ってくる前にしっかりと合図がある。
=> 【Mob420】アストロブレイズ実装

Asset/data/asset/functions/object/2168.general_long_laser/tick/.mcfunction
回転用にMarkerを自身の上に乗せているオブジェクトなのですが、消失時にそのマーカーを消し忘れていました
=> :adhesive_bandage: [Object2168] レーザーの消失時、マーカーが残りっぱなしだったのを修正

Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/laser/shoot/summon.mcfunction, Asset/data/asset/functions/object/2091.hyper_laser_manager/tick/summon_laser.mcfunction
- ツタンカーメン以外での使用も想定していたレーザーのオブジェクトですが、Y軸スケールを2で1ブロックから1で1ブロックになるように見た目を調整しました。リソースパック側の変更なので、オブジェクト側には変更が入っていません。
- この変更により、このオブジェクトを使っているツタンカーメンの一部攻撃の判定が見た目と一致しなくなったので、その修正です
=> ⚖️ [Mob372] ツタンカーメンのレーザー攻撃の判定周りの調整

Asset/data/asset/functions/mob/0338.corundum_twins/tick/app/skill/event_handler/01_crossfire/1.main.mcfunction, Asset/data/asset/functions/mob/0338.corundum_twins/tick/app/skill/event_handler/02_throw/1.main.mcfunction, Asset/data/asset/functions/mob/0338.corundum_twins/tick/app/skill/event_handler/03_launcher/1.main.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/init/.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/init/remove_bossbar.m.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/tick/app/skill/event_handler/05_hg_riderkick/1.main.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/tick/app/skill/event_handler/06_hg_punch/1.main.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/tick/app/skill/event_handler/07_1_hg_warpshot/1.main.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/tick/app/skill/event_handler/07_2_hg_heeloff/1.main.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/init/.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/init/remove_bossbar.m.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/03_2_kt_movetospear/1.main.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/05_1_kt_setwarp/1.main.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/07_1_kt_jumpslash/1.main.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/13_sc_warp/1.main.mcfunction, Asset/data/asset/functions/object/2200.twins_escape_animation/tick/event_rubiel.mcfunction, Asset/data/asset/functions/object/2200.twins_escape_animation/tick/event_sapphiel.mcfunction
- ルビエル、サフィエル単体のbossbarの消去処理をinitに追記
- 撤退アニメーション時、床の位置までゆっくり下がるようにした。床が無い場所で倒しても最大で6ブロックしか下がらないはずなので、奈落には落ちないと思う
- ワープ、ベクトル移動を含むターゲットの決定処理にdistanceを追加。遥か遠くまで追いかけることは無くなったと思う
=> 【Mob338】双子ボスバーなど修正

Asset/data/asset/functions/mob/0372.tutankhamen/load.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/dash_select.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/dash/charge/.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/dash/charge/check_collide.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/dash/charge/check_collide_back.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/dash/charge/move.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/dash/dash_slash/move.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/dash/side/move.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/stuck_revenge/.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/stuck_revenge/anger.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/stuck_revenge/break.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/stuck_revenge/explosion.mcfunction
- 埋まると上に登っていってしまうのを修正。埋まり防止処理は、それぞれ上下に空きがあるときのみ行うようになりました。(Fix #624 )
- 実はスポーン地点を囲われたりすると移動ができなくなっていたので、ブロックから抜け出す処理を追加。ついでに万が一埋まったときにも役立つでしょう(Fix #557 )
- 各移動処理をちょっと見直してちょっとだけ埋まりづらくなった…はず。それでもTPなので、埋まるときは埋まると思います。
=> 🚸 [Mob372] ツタンカーメンの調整

Asset/data/asset/functions/object/1059.book_of_hero/tick/.mcfunction, Asset/data/asset/functions/object/1059.book_of_hero/tick/attack.mcfunction, Asset/data/asset/functions/object/1059.book_of_hero/tick/kill.mcfunction
Fix #677 
・召喚できない問題を修正
・実際の攻撃属性が表記と異なるのを修正
・消滅演出を追加
=> 🐛 [神器1059] 召喚したオブジェクトが即座に消滅する問題を修正

Asset/data/asset/functions/mob/0377.grey_guardian_v2/remove/.mcfunction
=> 🐛 [Mob 377] 灰の守護者がremoveで消えない問題を修正

Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction, Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction, Asset/data/asset/functions/object/2113.rectangle_announce/summon/debug.mcfunction, Asset/data/asset/functions/object/2113.rectangle_announce/tick/transform.mcfunction
・Field.ToForwardを追加 (default : true)
trueなら今まで通り前に伸びる
falseにすると両方に伸びるようになる
=> [Object2113] 四角形予告の改善

Asset/data/asset/functions/artifact/0905.book_of_metastasis/trigger/2.check_condition.mcfunction
=> [神器0905] 転移の書をtpbanでは使用不可に

Asset/data/asset/functions/mob/1004.tultaria/tick/base_move/reset.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/base_move/teleport/.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/skill/fire/meteor_rain/meteor/summon.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/skill/fire/meteor_rain/pattern/1.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/skill/fire/move_shot/first_move.m.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/skill/light/stellar_fury_1/fall_start.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/skill/thunder/aiming_laser/move.m.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/skill/thunder/lightning_stab/targeting.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/skill/thunder/random_thunder/thunder/spread.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/skill/transition/phase_2_to_3/tick/attack/.mcfunction
- ランダムなプレイヤーの選択時に、範囲無制限、ディメンション関係なしで選択できてしまうのを修正。
- 上記の修正により、一部行動時に動作を完全停止してしまう問題も治るはずです
=> [Mob1004] ラスボスの問題のさらなる修正

Asset/data/asset/functions/object/1055.elemental_fish/summon/.mcfunction
=> :bug: [Artifact 1055] コール: エレメンタルファミリアで召喚される Mob が友好 Mob 扱いされていない問題を修正

Asset/data/asset/functions/artifact/0898.gale_pendant/give/2.give.mcfunction
=> [神器898] 疾風のペンダントの調整

Asset/data/asset/functions/effect/0202.sheep_blessing/tick/.mcfunction
=> 🚸 [Artifact 87] 羊の加護がライトブロックを置き換えられないのを修正

Asset/data/asset/functions/mob/0053.executioners/hurt/.mcfunction, Asset/data/asset/functions/mob/0053.executioners/hurt/backstep.mcfunction, Asset/data/asset/functions/mob/0053.executioners/register.mcfunction
=> 🚸 [Mob 53] 処刑人が負傷時にエフェクトの靄を出さないように修正 及び 索敵範囲の調整

Asset/data/asset/functions/artifact/1056.one_drop_of_life/give/2.give.mcfunction
=> [Artifact1056] 生命の一雫の説明を調整

Asset/data/asset/functions/mob/0187.flame_mage/summon/.mcfunction
ウォーターとサンダーには合ったのにフレイムにはなかった、なんで？
=> [Mob0187] フレイムメイジにAlawaySlowFallを追加

Asset/data/asset/functions/mob/0154.ruin/hurt/.mcfunction
=> [Mob0154] 破滅の演出の調整

Asset/data/asset/functions/artifact/1047.life_steal_emblem/give/2.give.mcfunction, Asset/data/asset/functions/artifact/1047.life_steal_emblem/trigger/0.load.mcfunction, Asset/data/asset/functions/artifact/1047.life_steal_emblem/trigger/3.main.mcfunction, Asset/data/asset/functions/effect/0260.life_steal/modifier/add.mcfunction, Asset/data/asset/functions/effect/0260.life_steal/register.mcfunction, Asset/data/asset/tags/functions/artifact/load.json
・不要なloadを破壊
・説明を修正
・補正量の計算を神器側で行い、Effect側にFieldOverrideを使って渡すように
=> [Artifact1047] 魂命の徽章の修正

Asset/data/asset/functions/artifact/1176.b_l_e_s_s/give/2.give.mcfunction, Asset/data/asset/functions/artifact/1176.b_l_e_s_s/trigger/2.check_condition.mcfunction, Asset/data/asset/functions/artifact/1176.b_l_e_s_s/trigger/3.main.mcfunction, Asset/data/asset/functions/artifact/1176.b_l_e_s_s/trigger/select_target.mcfunction, Asset/data/asset/functions/object/1094.aa_missile/register.mcfunction, Asset/data/asset/functions/object/1095.ag_missile/register.mcfunction, Asset/data/asset/functions/object/1095.ag_missile/tick/.mcfunction, Asset/data/asset/functions/object/1095.ag_missile/tick/accel_motion3.mcfunction, Asset/data/asset/functions/object/1095.ag_missile/tick/target_check.mcfunction
- バランス調整データ反映
- 敵がミサイル前方から外れたら強制的に当たりに行くようにして挙動の違和感削減
- 神器名修正
=> :balance_scale: [Artifact 1176] B.L.E.S.S.のダメージと挙動の改善及び神器名の修正

Asset/data/asset/functions/artifact/0605.ambition/trigger/3.main.mcfunction, Asset/data/asset/functions/artifact/0605.ambition/trigger/vfx/.mcfunction
演出処理での、ダメージと最大ダメージの割合計算において、割合が100を突破してしまうとフルパワー演出が見れないという問題があった
=> 🐛 [Artifact 605] 下克上の演出処理のミスを修正

Asset/data/asset/functions/effect/0014.receive_heal_debuff/_/end.mcfunction, Asset/data/asset/functions/effect/0014.receive_heal_debuff/_/given.mcfunction, Asset/data/asset/functions/effect/0014.receive_heal_debuff/_/re-given.mcfunction, Asset/data/asset/functions/effect/0014.receive_heal_debuff/_/register.mcfunction, Asset/data/asset/functions/effect/0014.receive_heal_debuff/_/remove.mcfunction, Asset/data/asset/functions/effect/0014.receive_heal_debuff/end/.mcfunction, Asset/data/asset/functions/effect/0014.receive_heal_debuff/given/.mcfunction, Asset/data/asset/functions/effect/0014.receive_heal_debuff/modifier/add.mcfunction, Asset/data/asset/functions/effect/0014.receive_heal_debuff/modifier/remove.mcfunction, Asset/data/asset/functions/effect/0014.receive_heal_debuff/re-given/.mcfunction, Asset/data/asset/functions/effect/0014.receive_heal_debuff/register.mcfunction, Asset/data/asset/functions/effect/0014.receive_heal_debuff/remove/.mcfunction, Asset/data/asset/functions/effect/0064.receive_heal_debuff/_/register.mcfunction, Asset/data/asset/functions/effect/0064.receive_heal_debuff/register.mcfunction, Asset/data/asset/functions/effect/0114.receive_heal_debuff/_/register.mcfunction, Asset/data/asset/functions/effect/0114.receive_heal_debuff/register.mcfunction, Asset/data/asset/functions/mob/0089.decapitation/attack/.mcfunction, Asset/data/asset/tags/functions/effect/end.json, Asset/data/asset/tags/functions/effect/given.json, Asset/data/asset/tags/functions/effect/re-given.json, Asset/data/asset/tags/functions/effect/register.json, Asset/data/asset/tags/functions/effect/remove.json
=> ⚖️ [Mob 89-90] 断切者の攻撃に被回復量低下の効果を追加

Asset/data/asset/functions/mob/0166.flying_potion/attack/debuff/damage.mcfunction
=> 🐛 [Mob 166] フライングポーションのダメージが防具値を無視しない問題を修正

.vscode/settings.json
=> :wrench: MobAsset の登録処理のみを生成した時 ID が入力されない問題を修正

Asset/data/asset/functions/artifact/0210.terra_blade/trigger/3.2.terra_shot_init.mcfunction, Asset/data/asset/functions/artifact/0210.terra_blade/trigger/event/random_position.mcfunction, Asset/data/asset/functions/artifact/0373.ice_sorcery/trigger/3.2.beamshot2.mcfunction, Asset/data/asset/functions/artifact/0573.final_prism/trigger/3.main.mcfunction, Asset/data/asset/functions/artifact/0607.u_and_w_06/trigger/3.main.mcfunction, Asset/data/asset/functions/artifact/0609.lunar_flare/trigger/projectile/summon_laser.mcfunction, Asset/data/asset/functions/artifact/1024.brave_rod/trigger/combo/beam1.mcfunction, Asset/data/asset/functions/artifact/1024.brave_rod/trigger/combo/beam3_burst.mcfunction, Asset/data/asset/functions/mob/0053.executioners/attack/.mcfunction, Asset/data/asset/functions/mob/0138.combat_turret/tick/2.2.ready.mcfunction, Asset/data/asset/functions/mob/0311.blazing_inferno/tick/base_move/passive_laser/summon.mcfunction, Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/firebomb/spread_ball.mcfunction, Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/ground_slam/laser/.mcfunction, Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/ground_slam/spread/.mcfunction, Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/ground_slam/spread/recursive.mcfunction, Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/rush_punch/punch/.mcfunction, Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/summon_minion/spread.mcfunction, Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/triple_fireball/shoot/any.mcfunction, Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/triple_fireball/shoot/triple.mcfunction, Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/laser/shoot/.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/skill/water/homing_shot/shot/.mcfunction, Asset/data/asset/functions/mob/1004.tultaria/tick/skill/water/homing_shot/shot/summon.mcfunction, Asset/data/asset/functions/mob/1005.illusion_of_loyalty/tick/moveset/skill/water/homing_shot/shot/.mcfunction, Asset/data/asset/functions/mob/1005.illusion_of_loyalty/tick/moveset/skill/water/homing_shot/shot/summon.mcfunction, Asset/data/asset/functions/object/1050.call_fulstuka/tick/1.skill_gun/3.ready.mcfunction, Asset/data/asset/functions/object/1082.soulfire_burst_bigshot/range_over/summon_small_shot.mcfunction
本当は全てのTagでやるべきなんだけど、開発しててSpreadMarkerが全体定義なのに耐えられなかった
=> 🧑‍💻 SpreadMarkerのTagの定義漏れを一括で修正

Asset/data/asset/functions/mob/0059.jack_o_lantern/_index.d.mcfunction, Asset/data/asset/functions/mob/0059.jack_o_lantern/death/.mcfunction, Asset/data/asset/functions/mob/0059.jack_o_lantern/remove/.mcfunction, Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/giant_pumpkin2/.mcfunction, Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/giant_pumpkin2/pos_type/line/4/1.mcfunction, Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/giant_pumpkin2/pos_type/line/4/2.mcfunction, Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/giant_pumpkin2/pos_type/line/4/3.mcfunction, Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/giant_pumpkin2/pos_type/line/4/4.mcfunction, Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/giant_pumpkin2/select_line.mcfunction, Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/skill/quiz/.mcfunction, Asset/data/asset/functions/object/2033.pumpkin_text_display/register.mcfunction, Asset/data/asset/functions/object/2033.pumpkin_text_display/summon/.mcfunction, Asset/data/asset/functions/object/2033.pumpkin_text_display/summon/debug.mcfunction, Asset/data/asset/functions/object/2033.pumpkin_text_display/tick/.mcfunction, Asset/data/asset/functions/object/alias/2033/register.mcfunction, Asset/data/asset/functions/object/alias/2033/summon.mcfunction, Asset/data/asset/functions/object/alias/2033/tick.mcfunction
=> ⚖ [Mob 59] ジャック・オ・ランタンの隙間避けで吸い込みを実装 & text_displayをObjectAssetへ移行

Asset/data/asset/functions/mob/0227.frost_eye/register.mcfunction, Asset/data/asset/functions/mob/0227.frost_eye/tick/debuff.mcfunction, Asset/data/asset/functions/mob/0228.frost_eye/register.mcfunction
=> ⚖ [Mob 228] フロストアイLv4が付与する鈍足の解除Lvを1に修正

Asset/data/asset/functions/mob/0365.frestchika/_index.d.mcfunction, Asset/data/asset/functions/mob/0365.frestchika/init/.mcfunction, Asset/data/asset/functions/mob/0365.frestchika/tick/base_move/.mcfunction, Asset/data/asset/functions/mob/0365.frestchika/tick/base_move/skill/charge_slash/windup.mcfunction, Asset/data/asset/functions/mob/0365.frestchika/tick/base_move/skill/cordinate_laser/windup.mcfunction, Asset/data/asset/functions/mob/0365.frestchika/tick/base_move/skill/front_dash_slash/start.mcfunction, Asset/data/asset/functions/mob/0365.frestchika/tick/base_move/skill/holo_block/windup.mcfunction, Asset/data/asset/functions/mob/0365.frestchika/tick/base_move/skill/random_teleport_slash/phase2/windup_1.mcfunction, Asset/data/asset/functions/mob/0365.frestchika/tick/base_move/skill/random_teleport_slash/teleport/.mcfunction, Asset/data/asset/functions/mob/0365.frestchika/tick/base_move/skill/random_teleport_slash/windup.mcfunction, Asset/data/asset/functions/mob/0365.frestchika/tick/base_move/skill/reset.mcfunction, Asset/data/asset/functions/mob/0365.frestchika/tick/base_move/skill/side_dash_shot/start.mcfunction
- AnimatedJavaの旧バージョンでエクスポートする必要があるとのことなのでやってみたところ、手持ちのアイテムを指定していた箇所のタグ名が変更されちゃったので修正
- ついでに、常時こっちを向くようになっていたのを、攻撃動作中はやらないように変更。
- ランダムワープ時のレーザー設置にサウンドが付きました。
=> 🐛[モブID 365] C.D.フレストチカのモデルのタグ名などを変更

Asset/data/asset/functions/artifact/0087.sheep_blessing/register.mcfunction, Asset/data/asset/functions/trader/2/register.mcfunction, Asset/data/asset/tags/functions/artifact/register.json
=> ⚖️ [Trader 2] 羊の加護を攻略進捗度で販売するように

Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/weapons/storm_shadow_cluster_prepare.mcfunction, Asset/data/asset/functions/object/2086.storm_shadow_cluster/kill/summon_munitions.mcfunction, Asset/data/asset/functions/object/2089.cluster_munition/register.mcfunction
- 全員スペクテーターになってると攻撃予想地点が出ない問題修正
- 弾頭にMobUUIDが伝達されていなかった問題を修正
=> 🐛 [Mob 213] TerribleSonicBomberの巡航ミサイル(クラスター弾)の不具合修正

Asset/data/asset/functions/artifact/0981.soulfire_burst/give/2.give.mcfunction, Asset/data/asset/functions/artifact/0981.soulfire_burst/trigger/3.main.mcfunction, Asset/data/asset/functions/artifact/0981.soulfire_burst/trigger/shoot.mcfunction, Asset/data/asset/functions/artifact/0981.soulfire_burst/trigger/summon_object.mcfunction, Asset/data/asset/functions/object/1083.soulfire_burst_smallshot/hit_entity/.mcfunction, Asset/data/asset/functions/object/1083.soulfire_burst_smallshot/recursive/.mcfunction, Asset/data/asset/functions/object/1083.soulfire_burst_smallshot/tick/.mcfunction, Asset/data/asset/functions/object/1083.soulfire_burst_smallshot/tick/homing.m.mcfunction
- 分裂する大弾ではなく、誘導する小型弾を放つ神器になりました。
- 子弾自体の誘導性も調整。めっちゃ当たるけど、あまりにも適当過ぎると当たらない感じ。「ボルテージストライカー」に少しエイム要求した感じ。
- 名前が「ソウルファイアシーカー」に名前が変わりました。
=> ⚖[神器ID 0981] ソウルファイアバーストの性能を調整

Asset/data/asset/functions/mob/0311.blazing_inferno/tick/base_move/passive_laser/.mcfunction, Asset/data/asset/functions/mob/0311.blazing_inferno/tick/base_move/passive_laser/summon.mcfunction
- 天使の召喚位置を勘違いしていたりしたなどの理由で、常時レーザーの発動地点は召喚位置から0.5下だったのですが、多分本番環境だと地面に埋まって見えなくなってしまうので修正。今まで報告が来なかったの、それだけ影が薄い攻撃なんでしょうね…
- Blesslessはやりたい放題らしいので、後半戦時の常時レーザーの数が2本増えました。大して変わりはしないでしょうが…。
=> ⚖[Mob 0311] ブレイジング・インフェルノの常時レーザーの発動地点が見えない問題を修正/ ついでに数が増えた

Asset/data/asset/functions/mob/0078.messenger_of_thunder/hurt/check_health.mcfunction, Asset/data/asset/functions/mob/0078.messenger_of_thunder/register.mcfunction, Asset/data/asset/functions/mob/0141.honey_archer/register.mcfunction, Asset/data/asset/functions/mob/0233.honey_flyer/register.mcfunction, Asset/data/asset/functions/mob/0330.aurora_reaper/attack/.mcfunction, Asset/data/asset/functions/mob/0330.aurora_reaper/register.mcfunction
=> 🧑‍💻 一部Mobが持つ武器のCustomModelDataを神器と統一

Asset/data/asset/functions/mob/1005.illusion_of_loyalty/tick/moveset/skill/thunder/random_thunder/windup.mcfunction
=> 🐛[Mob1005] 忠誠の幻想のアニメ再生処理にtweenじゃないのが混ざってた

Asset/data/asset/functions/mob/0055.hetukedah/tick/skill/otete_beam/beam/.mcfunction, Asset/data/asset/functions/mob/0055.hetukedah/tick/skill/otete_beam/big_beam/.mcfunction
Fix #1183
- 今やるべきではない感もありますが、目についたし修正楽だったので…
=> 🐛[Mob0055] ヘトゥケダウのビームのヒット時、プレイヤーの補正を使ってダメージを与えるのを修正

Asset/data/asset/functions/mob/0380.haruclaire_v3/tick/util/remove_animation_tag.mcfunction
- remove_animation_tag から、一部のアニメーションのタグが抜けていたので修正。それ以外の変更は無し
=> [MOB 380]フェーズ移行時に一部アニメーションが停止しない問題を修正

Asset/data/asset/functions/mob/0440.dps_checker_fragile/death/.mcfunction, Asset/data/asset/functions/mob/0440.dps_checker_fragile/summon/m.mcfunction
- コア側のトレーニングエリアの処理で再召喚を担うようになったため。
=> :recycle: [Mob 0440] もろい訓練用の人形の死亡処理から自身の再召喚処理を削除

Asset/data/asset/functions/artifact/0105.secret_meat/give/2.give.mcfunction, Asset/data/asset/functions/artifact/0105.secret_meat/trigger/3.main.mcfunction, Asset/data/asset/functions/artifact/0317.sea_storm_sword/give/2.give.mcfunction, Asset/data/asset/functions/artifact/0317.sea_storm_sword/trigger/vfx.mcfunction, Asset/data/asset/functions/artifact/0976.brave_sword/give/2.give.mcfunction, Asset/data/asset/functions/artifact/1021.brave_book/give/2.give.mcfunction, Asset/data/asset/functions/artifact/1024.brave_rod/give/2.give.mcfunction, Asset/data/asset/functions/effect/0203.secret_meat/register.mcfunction
- 謎肉: 「ナゾの肉」に名称変更。説明文ちょっと変わった。
- ブレイブ系3種: 文字色ピンクではないなって思ったので青くした。
- 荒波の剣: どう見ても荒波な見た目ではないので「氷晶の剣」に名前を変えて、演出もちょっと調整した。
=> ♻️ 思うところがあった神器の名前や説明文、そして演出を変更

Asset/data/asset/functions/object/2150.haruclaire_ice_wall/tick/kill.mcfunction
- プレイを見ていてパーティクルが多くて視認性が悪そうだったので、アイスウォール消滅時のパーティクルを削減
- 余裕あったら適用してほしいです
=> [MOB 380]ハルクレア調整

Asset/data/asset/functions/mob/0327.eclael/tick/app.general/3.stop_all_animations.mcfunction
- 一部アニメーションタグが抜けていた。大技を連発した原因はおそらくこれだと思う
- Issue
- #1416
=> [MOB 327]アニメーション停止処理のタグ漏れを修正

Asset/data/asset/functions/mob/0442.dps_checker_magical/register.mcfunction
=> 🐛 [Mob 442] 魔法耐性の人形のIDが正しくない問題を修正

Asset/data/asset/functions/mob/0410.heiloang/death/.mcfunction, Asset/data/asset/functions/mob/0410.heiloang/remove/.mcfunction
- remove時、眷属のremoveを呼び出すようにした。通常あり得ないが、念のためdeath時も同様
=> :bug: [Mob 410] 黒龍に敗北した場合に眷属が残る問題を修正

Asset/data/asset/functions/mob/0437.lawless_iron_doll/tick/base_move/skill/super_slam/fall.mcfunction, Asset/data/asset/functions/mob/0437.lawless_iron_doll/tick/base_move/skill/super_slam/tick.mcfunction
Fix #1422 
- 敵に持続して残るようなmarkerを置いておく、とかで誘発できたんだと思う
=> 🐛 [Mob 0437] 必殺の落下攻撃時、着地ポイント以外のマーカーでも着地を中断できていたのを修正

Asset/data/asset/functions/artifact/0733.percentage_sword/trigger/2.check_condition.mcfunction, Asset/data/asset/functions/artifact/0733.percentage_sword/trigger/3.main.mcfunction
Fix #1484
多分distance=..6だとExtendedCollision相手だと狭いとかそんななのかな...?
それと、Uninterferableを殴った際に終わるって問題も直した
=> 🐛 [Artifact 733] 百分一剣が特定条件下でダメージが設定されない問題を修正

Asset/data/asset/functions/artifact/1024.brave_rod/trigger/combo/beam1.mcfunction, Asset/data/asset/functions/artifact/1024.brave_rod/trigger/combo/beam1_shot.mcfunction, Asset/data/asset/functions/artifact/1024.brave_rod/trigger/combo/beam3_burst.mcfunction, Asset/data/asset/functions/artifact/1024.brave_rod/trigger/combo/beam3_shot.mcfunction, Asset/data/asset/functions/artifact/1024.brave_rod/trigger/combo/laser.mcfunction, Asset/data/asset/functions/artifact/1024.brave_rod/trigger/combo/laser_finish.mcfunction
- 確かに前までの使用音はデカかった。連射武器だからなおさら。
- 今回は音量を下げただけですが、もっと地味な音にするとかそういうのでもいいのかも。
- この際なので前から気になっていたビームの見た目を強化。ツタンカーメンやトゥルとかが使うタイプのビームになりました。
=> 💫[Artifact 1024] ブレイブロッドの使用時の音量調整と、ビームの見た目の強化

Asset/data/asset/functions/mob/0155.immorality/register.mcfunction, Asset/data/asset/functions/mob/0155.immorality/tick/.mcfunction, Asset/data/asset/functions/mob/0155.immorality/tick/announce/.mcfunction, Asset/data/asset/functions/mob/0155.immorality/tick/announce/recursive_line.mcfunction, Asset/data/asset/functions/mob/0155.immorality/tick/shot/damage.mcfunction, Asset/data/asset/functions/mob/0155.immorality/tick/shot/reset.mcfunction, Asset/data/asset/functions/mob/0155.immorality/tick/shot/shoot.mcfunction
・攻撃前に予告を出すように
・難易度比例で攻撃間隔が短くなる仕様を廃止
=> ⚖ [Mob 155] 背徳の調整

Asset/data/asset/functions/mob/0338.corundum_twins/0.load.mcfunction, Asset/data/asset/functions/mob/0338.corundum_twins/app/call_from_twins/5.idle_timer.mcfunction, Asset/data/asset/functions/mob/0338.corundum_twins/init/app/2.summon_twins.mcfunction, Asset/data/asset/functions/mob/0338.corundum_twins/tick/.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/_index.d.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/app/call_from_root/1.interrupt.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/tick/app/skill/event_handler/02_hg_idle/1.main.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/tick/app/skill/event_handler/06_1_hg_lowkick/5.1.damage_down.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/tick/app/skill/event_handler/40_1_damage_start/1.main.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/tick/app/skill/event_handler/40_2_damage_down/1.main.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/tick/app/skill/event_handler/40_3_damage_end/1.main.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/tick/app/skill/event_handler/40_5_damage_stun/1.main.mcfunction, Asset/data/asset/functions/mob/0339.twins_sapphiel/tick/app/skill/select/7.return.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/_index.d.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/app/call_from_root/1.interrupt.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/02_kt_idle/1.main.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/08_2_kt_throw/5.1.damage_catch.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/08_2_kt_throw/5.3.damage_down.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/31_2_sync_crossfire_upper/5.damage.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/40_1_damage_start/1.main.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/40_2_damage_down/1.main.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/40_3_damage_end/1.main.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/event_handler/40_5_damage_stun/1.main.mcfunction, Asset/data/asset/functions/mob/0340.twins_rubiel/tick/app/skill/select/7.return.mcfunction
- サフィが消える問題
- ダウン中の移動、ダウン後の復帰などに中心点との距離に応じた分岐を追加
- 中心点から離れすぎている場合は中心に帰るよう修正
- 上記変更により、役割を放棄してどこかに遊びに行くことは少なくなったと思う。ただし、双子の気分次第なので完全に治せているかはわからない
- #1425
- #1536
- 双子が使用するEffectをEffectAssetに変更
- #1520
- 場当たり的対策ではあるものの、双子が同時に待機（動かなくなった）場合のみ増加するスコアを追加。それが一定以上になった場合、強制的にシンクロ攻撃を発動して状況を改善する
- #719
=> [Mob 338] 双子 Issue対応

Asset/data/asset/functions/mob/0410.heiloang/init/locator.mcfunction, Asset/data/asset/functions/mob/0410.heiloang/tick/debug/interrupt.mcfunction, Asset/data/asset/functions/mob/0410.heiloang/tick/event/final_flare/damage.mcfunction, Asset/data/asset/functions/mob/0410.heiloang/tick/event/heil_disaster/.mcfunction, Asset/data/asset/functions/mob/0410.heiloang/tick/event/heil_disaster/hard.mcfunction, Asset/data/asset/functions/mob/0410.heiloang/tick/event/sweep/.mcfunction, Asset/data/asset/functions/mob/0410.heiloang/tick/event/sweep/attack.mcfunction, Asset/data/asset/functions/mob/0410.heiloang/tick/event/sweep/attack_damage.mcfunction, Asset/data/asset/functions/mob/0410.heiloang/tick/event/sweep/attack_loop.mcfunction, Asset/data/asset/functions/mob/0411.behemoth/init/locator.mcfunction, Asset/data/asset/functions/mob/0411.behemoth/tick/event/offering_end/.mcfunction, Asset/data/asset/functions/mob/0411.behemoth/tick/event/terzetto_purgatorio/attack.m.mcfunction, Asset/data/asset/functions/mob/0411.behemoth/tick/util/end_armor_locator.mcfunction, Asset/data/asset/functions/mob/0412.tiamat/init/locator.mcfunction, Asset/data/asset/functions/mob/0412.tiamat/tick/event/offering_end/.mcfunction, Asset/data/asset/functions/mob/0412.tiamat/tick/util/end_armor_locator.mcfunction, Asset/data/asset/functions/object/2127.heiloang_ice_vfx/init/.mcfunction, Asset/data/asset/functions/object/2127.heiloang_ice_vfx/summon/.mcfunction, Asset/data/asset/functions/object/2175.tiamat_ice_vfx/init/.mcfunction, Asset/data/asset/functions/object/2175.tiamat_ice_vfx/summon/.mcfunction, Asset/data/asset/functions/object/2182.heiloang_thunderball/tick/damage.mcfunction, Asset/data/asset/functions/object/2182.heiloang_thunderball/tick/kill.mcfunction
- 当たり判定を RotatedDX に変更し、厳密化
- Fix #1555
- Hard, Blesslessでの即死判定の厳密化
- および、ダメージが 100% を超えた場合は 9999.0 固定になるよう変更
- Fix #1544
- デスログに%2$sを使うよう修正
- Fix #1505
- 黒龍のロックオン雷、焔竜のロックオンフレアブレスのダメージ判定にdistanceを追加
- Fix #1491
- ArmorDropChancesを0に変更
- Fix #1412
- 以下については、召喚位置を基準にしているので埋まることは普通無い。無法と同じく、実環境で召喚位置が上下にずれる問題の影響かもしれない
- 暫定策として、item_displayのbrightnessを15に固定。夜でも光り輝いてしまうけど、雷なども光っているので問題ない気はする
- Fix #1438
=> [Mob 410] 黒龍Issue対応

Asset/data/asset/functions/mob/0380.haruclaire_v3/_index.d.mcfunction, Asset/data/asset/functions/mob/0380.haruclaire_v3/death/.mcfunction, Asset/data/asset/functions/mob/0380.haruclaire_v3/init/.mcfunction, Asset/data/asset/functions/mob/0380.haruclaire_v3/remove/.mcfunction, Asset/data/asset/functions/mob/0380.haruclaire_v3/tick/debug/interrupt.mcfunction, Asset/data/asset/functions/mob/0380.haruclaire_v3/tick/event/ice_pillar/.mcfunction, Asset/data/asset/functions/mob/0380.haruclaire_v3/tick/event/ice_pillar/attack.mcfunction, Asset/data/asset/functions/mob/0380.haruclaire_v3/tick/event/ice_pillar_duo/.mcfunction, Asset/data/asset/functions/mob/0380.haruclaire_v3/tick/event/ice_pillar_duo/attack.mcfunction, Asset/data/asset/functions/mob/0380.haruclaire_v3/tick/event/ice_spear/.mcfunction, Asset/data/asset/functions/object/2156.haruclaire_icepillar/init/.mcfunction
- アイススピアが想定より早く発生して回避不能になっていたっぽいので、発生を遅くした。たぶんダメージを下げる必要はない
- Fix #1545
- ハルクレアのkillまたはremobe時に、消えない氷像を飾っていく問題を修正。実行順が駄目だったようだ
- Fix #1431
- マルチにおいて、アイスピラーを複数同時設置する場合においても、全て回転方向を揃えて出すよう修正。プレイヤー全員で時計/半時計に回れば回避不能パターンは生まれないはず
- 召喚位置を少しずらして、お辞儀を見えやすくした
=> [Mob 380] ハルクレアのバグ修正およびUX向上

Asset/data/asset/functions/artifact/0724.oblivious_snow/give/2.give.mcfunction, Asset/data/asset/functions/artifact/0725.oblivious_snow/give/2.give.mcfunction, Asset/data/asset/functions/artifact/0726.oblivious_snow/give/2.give.mcfunction, Asset/data/asset/functions/artifact/0727.oblivious_snow/give/2.give.mcfunction
=> 🐛 [Artifact 724-727] 忘却の白雪装備のダメージ表記ミスを修正
